### ISSUE TITLE
Average predictions for multilevel Bayesian model

### ISSUE THREAD

**Issue by araikes** [vincentarelbundock/marginaleffects#1201] opened 2024-08-27 22:56 UTC
Hi,

I have a question about the potential for `marginaleffects` to meet a need. I work in neuroimaging and have begun using `brms` to fit multilevel Bayesian models to provide estimates of group differences in multiple brain regions simultaneously. I'm fitting models that look like the following:
`fa.z ~ 1 + SEX * CARRIER + age.c + (1 | Subj) + (1 + SEX * CARRIER + age.c | ROI)`
 
where SEX and CARRIER are two-level factors (contrasts = contr.sum) that code Male/Female and Carrier/Non-carrier respectively. Subj is a factor identifying the participant and ROI is a 72-level factor specifying a given region of the brain. E.g.:
```
  Subj    ROI     SEX   CARRIER     age.c         fa.z
  <fct>   <fct>   <fct> <fct>       <dw_trnsf>   <dbl>
1 sub-087 AF_left Male  Non-carrier  0.33724538 -0.501
2 sub-195 AF_left Male  Carrier      0.33724538  1.15 
3 sub-287 AF_left Male  Non-carrier  0.06744908 -1.85 
4 sub-339 AF_left Male  Carrier     -0.60704168 -0.140
5 sub-403 AF_left Male  Non-carrier  0.33724538 -0.924
6 sub-513 AF_left Male  Carrier      0.20234723  0.506
```

I understand that I could use `marginaleffects` to get the marginal posterior effects for SEX and CARRIER for the fixed effects. Is there a way to use the package to get the adjusted posteriors and contrasts for each SEX/CARRIER combination at the ROI level? I'm sure that I can and I'm just not seeing the path toward it.

**Comment by vincentarelbundock** [comment] 2024-08-27 23:10
I don't understand what specific mathematical quantity you want. Can you formulate it in terms of a causal effect?

What is the effect of increasing X by 1 unit when Z=5?

**Comment by araikes** [comment] 2024-08-27 23:43
I'm probably gonna butcher this trying to translate between my thinking and yours, so bear with it...

What is the effect of SEX going from Male to Female when Carrier = "Carrier", but at each level of ROI.

**Comment by vincentarelbundock** [comment] 2024-08-27 23:50
> What is the effect of SEX going from Male to Female when Carrier = "Carrier", but at each level of ROI.

Sounds reasonable. How about:

```r
comparisons(model,
  variables = "SEX",
  newdata = datagrid(Carrier = "Carrier", ROI = unique))
```

`variables` defines the variables we "intervene" on. `newdata` defines the values of the covariates we are interested in. Note that all unspecified covariates in the model will be held at their mean or model.

**Comment by vincentarelbundock** [comment] 2024-08-27 23:50
Or if you want to average:

```r
comparisons(model,
  variables = "SEX",
  by = c("Carrier", "ROI"))
```

and you filter out the `Carrier` values you don't care about.

**Comment by vincentarelbundock** [comment] 2024-08-27 23:53
This is not a bug report or a feature request, so I'll close this. Good luck.

**Closed by vincentarelbundock** 2024-08-27 23:52 UTC

**Comment by araikes** [comment] 2024-08-27 23:54
Ah, interesting.

Thanks
