### ISSUE TITLE
Two problems with `inferences()`

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#851] opened 2023-07-31 21:24 UTC
Two problems with `inferences()` that I noticed in Andrew's document. First is that the predictor levels are in the opposite order to how they are in the `avg_predictions()` output. Second is that the estimates themselves are different when using the simulation method for inference, but only the SEs/CIs should be different. Are you using the posterior mean of the simulation distribution? If so, you should just use the original estimates. [This paper](https://doi.org/10.1017/psrm.2023.8) explains why using the mean of the simulation distribution is incorrect.

**Comment by vincentarelbundock** [comment] 2023-08-09 19:13
A few comments.

Sorting output is a surprisingly difficult problem, which has caused a lot of bugs in the past.

Typically, the results are sorted in the order in which they appear in the `by` columsn of the original dataset. My guess is that the results appear in a different order because the bootstrap shuffles the rows. This could be a not-so-bad issue, or the sign of a big problem: are replicates correctly `cbind`-ed with their matching rows? I don't know yet.

All the potential solutions I can come up with have problems. Some notes to self:

* Need to sort rows before `get_hypothesis()` is called.
  - Problem: This is called in the "inner" functions `get_contrast` and `get_predictions`, which are called twice for every coefficient in the model when computing standard errors. Sorting could thus be very computationally costly.
* Need to sort both the main output and the `draws` objects in the same way.
* One approach would be to sort `newdata` in `sanitize_newdata()` based on the value of `by`. This would only require sorting once, and it should group in the right order. The problem is that this doesn't allow sorting on `term` or contrast label, which would be very nice to have.

I really want to come up with a permanent solution for this before 1.0.0, but I'm not sure what it should be.

**Comment by vincentarelbundock** [comment] 2023-08-09 20:59
Maybe I can just sort newdata when by is a vector and variables when it is NULL. That probably gets us near the goal, and should be one shot operations.

**Comment by vincentarelbundock** [comment] 2023-08-10 15:01
> Would it not be easier to simply sort the output dataframe after all quantities have been generated?

No, because `get_hypothesis()` would then be applied before sorting. There would be no way for the user to know what `b1=b3` because the output would be different than the internal data frame to which the 1 and 3 indices refer.

**Comment by vincentarelbundock** [comment] 2023-08-13 20:17
OK, I think I’ve got it fixed on Github.

Point estimates with simulation are the same as the default:

``` r
library(marginaleffects)
mod <- glm(vs ~ hp + mpg + am, data = mtcars, family = binomial)

cmp <- avg_comparisons(mod)
cmp |> inferences(method = "simulation", R = 500)
# 
#  Term Contrast Estimate Std. Error    2.5 %   97.5 %
#   am     1 - 0 -0.22688    0.09945 -0.37951 5.07e-03
#   hp     +1    -0.00543    0.00227 -0.00867 7.79e-06
#   mpg    +1     0.01368    0.01715 -0.02071 4.97e-02
# 
# Columns: term, contrast, estimate, std.error, conf.low, conf.high
cmp
# 
#  Term Contrast Estimate Std. Error     z Pr(>|z|)    S    2.5 %   97.5 %
#   am     1 - 0 -0.22688    0.06834 -3.32   <0.001 10.1 -0.36083 -0.09293
#   hp     +1    -0.00543    0.00191 -2.84   0.0045  7.8 -0.00917 -0.00168
#   mpg    +1     0.01368    0.01085  1.26   0.2073  2.3 -0.00758  0.03494
# 
# Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
```

Sort order makes sense and seems the same with bootstrap:

``` r
mod <- lm(mpg ~ factor(cyl), mtcars)
avg_predictions(mod, by = "cyl")
# 
#  cyl Estimate Std. Error    z Pr(>|z|)     S 2.5 % 97.5 %
#    4     26.7      0.972 27.4   <0.001 548.1  24.8   28.6
#    6     19.7      1.218 16.2   <0.001 193.8  17.4   22.1
#    8     15.1      0.861 17.5   <0.001 226.1  13.4   16.8
# 
# Columns: rowid, cyl, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, rowid_dedup

mod <- nnet::multinom(factor(cyl) ~ mpg + hp, data = mtcars, trace = FALSE)

avg_predictions(mod)
# 
#  Group Estimate Std. Error    z Pr(>|z|)   S 2.5 % 97.5 %
#      4    0.344   0.000764  450   <0.001 Inf 0.342  0.345
#      6    0.219   0.000876  250   <0.001 Inf 0.217  0.220
#      8    0.437   0.000429 1021   <0.001 Inf 0.437  0.438
# 
# Columns: group, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high

avg_predictions(mod) |> inferences(method = "boot", R = 25)
# 
#  Group Estimate Std. Error  2.5 % 97.5 %
#      4    0.344     0.0342 0.3072  0.437
#      6    0.219     0.0441 0.0939  0.298
#      8    0.437     0.0259 0.3758  0.469
# 
# Columns: group, estimate, std.error, conf.low, conf.high

avg_predictions(mod) |> inferences(method = "fwb", R = 25)
# 
#  Group Estimate Std. Error 2.5 % 97.5 %
#      4    0.344     0.0932 0.142  0.506
#      6    0.219     0.0783 0.107  0.386
#      8    0.437     0.0853 0.315  0.604
# 
# Columns: group, estimate, std.error, conf.low, conf.high

avg_predictions(mod) |> inferences(method = "rsample", R = 25)
# 
#  Group Estimate 2.5 % 97.5 %
#      4    0.344 0.308  0.399
#      6    0.219 0.133  0.274
#      8    0.437 0.399  0.469
# 
# Columns: group, estimate, conf.low, conf.high
```

**Closed** 2023-08-13 20:43 UTC
