### ISSUE TITLE
Environment issues (?) calling datagrid inside a function

### ISSUE THREAD

**Issue by NickCH-K** [vincentarelbundock/marginaleffects#769] opened 2023-05-08 03:05 UTC
I've found that, if I put a `slopes()` or `predictions()` call with a `datagrid()` inside of a function, then that `datagrid()` cannot access any arguments passed into the function.

```r
library(fixest)
library(marginaleffects)

data(mtcars)

m = feglm(am ~ mpg + hp, data = mtcars, family = 'logit')

qtiles = quantile(mtcars$mpg, c(.25, .5, .75))

# Works fine
slopes(m)
# Works fine
slopes(m, newdata = datagrid(mpg = qtiles))

# Now what if I put it in a function
get_slopes_at_value = function(m, q) {
  slopes(m, newdata = datagrid(mpg = q))
}
get_slopes_at_value(m = m, q = qtiles)
# Error in at[[n]](newdata[[n]]) :
# one of "yes", "no", "ask" or "default" expected.

# If I specify the model (as you would do if calling datagrid() outside of slopes() it works again
get_slopes_at_value = function(m, q) {
  slopes(m, newdata = datagrid(mpg = q, model = m))
}
get_slopes_at_value(m = m, q = qtiles)
```

I suspect this might be an environment issue - the error I was getting initially when encountering this was "object q not found" but for some reason I can't replicate this in the simplified example.

**Comment by vincentarelbundock** [comment] 2023-05-08 05:44
Yes, you are almost certainly right: an environment issue. The problem is that we use `insight::get_data()` to retrieve the dataset. That function must look at the model call and search the environments for an object with the same name. 

This is actually a very tricky problem, but there's a Pull Request in `insight` to improve the situation. Hopefully it helps. https://github.com/easystats/insight/pull/761

Note that `datagrid` also accepts a `newdata` argument. When using `datagrid` inside a function, it might be safer to supply both `model` and `newdata`, and perhaps to proceed in two steps: (1) assign a `nd` object and (2) feed it to `slopes(newdata=nd)`.

**Comment by capnrefsmmat** [comment] 2023-05-08 15:09
You piqued my interest, so I took a look. Unfortunately my `get_data()` pull request doesn't fix this issue, but I think the issue is actually slightly different here.

The problem is not in the data obtained from `m`. It's that in `get_slopes_at_value`, there's an argument called `q`... and `slopes()` is somehow interpreting that as the function `q()`, not as the argument passed into the function, the quantiles.

I think that's because `slopes()` calls `substitute()` on its `newdata` argument, so it can `eval()` it in a particular way, and that `eval()` isn't using the right environment. Hence it finds the wrong `q` when evaluating. I think passing the right environment to `sanitize_newdata_call()` could fix the issue, e.g. by having `slopes()` pass the `parent.frame()` so `sanitize_newdata_call()` can pass that to `eval()`.

**Comment by vincentarelbundock** [comment] 2023-05-08 15:19
Oh wow, that's a fun one! Does it work when you rename it inside the function?


```r
get_slopes_at_value = function(m, q) {
  z <- q
  slopes(m, newdata = datagrid(mpg = z))
}
```

I'd like to find a solution, but won't be able to look at this in the short run. Still probably should not use q as an argument or object name in R...

**Comment by capnrefsmmat** [comment] 2023-05-08 15:42
That produces the following:

```
> get_slopes_at_value(m = m, q = qtiles)
Error in datagrid(mpg = z, model = list(nobs = 32L, nobs_origin = 32L,  : 
  object 'z' not found
```

I think that's for the same reason: the `eval()` uses `sanitize_newdata_call()` as the scope, so it will only have access to variables accessible there, or (presumably?) in the global environment. `z` is in neither.

But I haven't tested this out thoroughly. Are there examples in tests or vignettes where `slopes()` works with `newdata` referring to a different environment?

**Comment by vincentarelbundock** [comment] 2023-05-10 18:39
Thanks a lot @NickCH-K for the report and @capnrefsmmat for the investigation. I really appreciate it\!

This should now be fixed in version 0.11.1.9014 on Github:

``` r
library(fixest)
library(marginaleffects)
data(mtcars)
m = feglm(am ~ mpg + hp, data = mtcars, family = 'logit')
qtiles = quantile(mtcars$mpg, c(.25, .5, .75))
get_slopes_at_value = function(m, q) {
  slopes(m, newdata = datagrid(mpg = q))
}
get_slopes_at_value(m = m, q = qtiles)
# 
#  Term Estimate Std. Error     z Pr(>|z|)     2.5 %   97.5 %  hp  mpg
#   hp  0.000123   0.000276 0.445   0.6566 -0.000419 0.000664 147 15.4
#   hp  0.009023   0.004120 2.190   0.0285  0.000949 0.017098 147 19.2
#   hp  0.002092   0.002525 0.829   0.4073 -0.002857 0.007041 147 22.8
#   mpg 0.002813   0.006314 0.446   0.6559 -0.009562 0.015189 147 15.4
#   mpg 0.206569   0.083348 2.478   0.0132  0.043210 0.369928 147 19.2
#   mpg 0.047846   0.057720 0.829   0.4071 -0.065283 0.160974 147 22.8
# 
# Columns: rowid, term, estimate, std.error, statistic, p.value, conf.low, conf.high, predicted, predicted_hi, predicted_lo, am, hp, mpg
```

**Closed by vincentarelbundock** 2023-05-10 18:39 UTC

**Comment by capnrefsmmat** [comment] 2023-05-11 14:22
Something that might be helpful to you in the future: In my own package, I also need to `eval()` code in the user's environment, and I recently found that rlang's [quosures](https://adv-r.hadley.nz/evaluation.html#quosures) make this much easier.

Basically, instead of using `substitute()`, you use `enquo()`. That captures the un-evaluated argument *and also the environment it came from*. Later, you use `eval_tidy()` to eval the code, and it uses the correct environment automatically. No need to use `parent.frame()` to try to find it, and so it'd work with any bizarre combination of functions and closures and so on.

**Comment by vincentarelbundock** [comment] 2023-05-11 14:39
> Something that might be helpful to you in the future: In my own package, I also need to `eval()` code in the user's environment, and I recently found that rlang's [quosures](https://adv-r.hadley.nz/evaluation.html#quosures) make this much easier.
> 
> Basically, instead of using `substitute()`, you use `enquo()`. That captures the un-evaluated argument _and also the environment it came from_. Later, you use `eval_tidy()` to eval the code, and it uses the correct environment automatically. No need to use `parent.frame()` to try to find it, and so it'd work with any bizarre combination of functions and closures and so on.

Thanks, that's useful. I think I'll wait a bit to see if new problems pop up, but if I notice issues in the future I might bite the bullet and onboard the `rlang` dependency.

**Comment by grantmcdermott** [comment] 2023-05-26 17:00
> Thanks, that's useful. I think I'll wait a bit to see if new problems pop up, but if I notice issues in the future I might bite the bullet and onboard the rlang dependency.

FWIW [`data.table::substitute2`](https://rdatatable.gitlab.io/data.table/reference/substitute2.html) also does better environment checking than the base counterpart. So that's a potential option instead of taking of an additional dependency... but only once the (never-ending) dev version of **data.table** finally makes its way onto CRAN 🙄

**Comment by vincentarelbundock** [comment] 2023-05-26 17:02
thanks, will look into it.
