### ISSUE TITLE
Missing response categories for cumulative models when groups not present in `predicted_lo`

### ISSUE THREAD

**Issue by bwiernik** [vincentarelbundock/marginaleffects#639] opened 2023-02-03 16:58 UTC
I have a sample of 5-point ordinal data. When running `comparisons()`, only the bottom 3 response groups end up in `predictions_lo` and the top 3 response groups end up in `predictions_hi`. As a result, when `out` is returned, it only has comparisons for the bottom 3 categories.

```
library(marginaleffects)

d <- read.csv("example_data.csv") |>
  transform(x = factor(x), y = ordered(y))

m <- brms::brm(
  y | weights(n) ~ x, 
  data = d,
  family = "cumulative"
)

avg_comparisons(m)

#' > avg_comparisons(m)
#' 
#'  Group Term Contrast Estimate    2.5 %    97.5 %
#'      1    x    1 - 0 -0.07396 -0.11746 -0.031294
#'      2    x    1 - 0 -0.03490 -0.08305  0.009597
#'      3    x    1 - 0  0.15865  0.11966  0.200865
#' 
#' Prediction type:  response 
#' Columns: type, group, term, contrast, estimate, conf.low, conf.high 
```

[example_data.csv](https://github.com/vincentarelbundock/marginaleffects/files/10580995/example_data.csv)

**Comment by vincentarelbundock** [comment] 2023-02-04 04:27
Thanks a lot for the reprex. Yes, definitely a bug. Very sorry about that\!

Should be fixed on Github. Do these estimates make sense substantively?

``` r
library(marginaleffects)
library(brms)

dat <- structure(list(y = structure(c(1L, 1L, 2L, 2L, 3L, 3L, 4L, 4L, 
5L, 5L), levels = c("1", "2", "3", "4", "5"), class = c("ordered", 
"factor")), x = structure(c(1L, 2L, 1L, 2L, 1L, 2L, 1L, 2L, 1L, 
2L), levels = c("0", "1"), class = "factor"), n = c(102L, 50L, 
97L, 84L, 9L, 11L, 89L, 130L, 38L, 59L)), class = "data.frame", row.names = c(NA, 
-10L))
dat <- transform(dat, x = factor(x), y = ordered(y))

m <- brms::brm(
  y | weights(n) ~ x, 
  data = dat,
  family = "cumulative")
```

``` r
avg_predictions(m)
#  Group Estimate   2.5 % 97.5 %
#      1   0.2278 0.19718 0.2598
#      2   0.2708 0.23916 0.3064
#      3   0.0306 0.01913 0.0454
#      4   0.3248 0.29100 0.3608
#      5   0.1439 0.11979 0.1716
# 
# Prediction type:  response 
# Columns: type, group, estimate, conf.low, conf.high

avg_comparisons(m)
#  Group Term Contrast   Estimate     2.5 %   97.5 %
#      1    x    1 - 0 -0.1304047 -0.180614 -0.08240
#      2    x    1 - 0 -0.0562000 -0.083192 -0.03431
#      3    x    1 - 0  0.0006711 -0.001127  0.00281
#      4    x    1 - 0  0.0957969  0.060028  0.13535
#      5    x    1 - 0  0.0903140  0.056415  0.12840
# 
# Prediction type:  response 
# Columns: type, group, term, contrast, estimate, conf.low, conf.high
```

**Comment by bwiernik** [comment] 2023-02-04 08:30
Those look right. I'll double check my manual computations on these data tomorrow

**Comment by vincentarelbundock** [comment] 2023-02-06 19:14
Closing to clean up the repo, not to put pressure on you. I'd still be interested in knowing if this is confirmed.

Feel free to keep commenting if the problem is not resolved.

**Closed by vincentarelbundock** 2023-02-06 19:14 UTC

**Comment by bwiernik** [comment] 2023-02-07 01:44
Yep, it matches my manual computations

```
library(marginaleffects)
library(brms)

median_ci <- function (x, estimate_name = "estimate", ci = 0.95) {
  tail <- (1 - ci)/2
  out <- tibble::tibble(`:=`({{estimate_name}}, median(x)), CI = ci, CI_low = as.vector(quantile(x, probs = tail)), 
  CI_high = as.vector(quantile(x, probs = 1 - tail)))
  out
}


dat <-
  structure(
    list(
      y = structure(c(1L, 1L, 2L, 2L, 3L, 3L, 4L, 4L, 5L, 5L), levels = c("1", "2", "3", "4", "5"), class = c("ordered", "factor")),
      x = structure(c(1L, 2L, 1L, 2L, 1L, 2L, 1L, 2L, 1L, 2L), levels = c("0", "1"), class = "factor"),
      n = c(102L, 50L, 97L, 84L, 9L, 11L, 89L, 130L, 38L, 59L)
    ),
    class = "data.frame",
    row.names = c(NA, -10L)
  )

m <- brms::brm(
  y | weights(n) ~ x, 
  data = dat,
  family = "cumulative")

tidybayes::add_epred_rvars(
  newdata = data.frame(x = c(0, 1)),
  object = m
) |> 
  mutate(.epred = as.data.frame(.epred)) |> 
  unpack(.epred) |> 
  summarise(across(`1`:`5`, posterior::rvar_mean)) |> 
  pivot_longer(everything(), names_to = "group", values_to = ".epred") |> 
  mutate(median_ci(.epred))
  
#' # A tibble: 5 × 6
#'   group          .epred estimate    CI CI_low CI_high
#'   <chr>      <rvar[1d]>    <dbl> <dbl>  <dbl>   <dbl>
#' 1 1      0.227 ± 0.0157   0.227   0.95 0.197   0.258 
#' 2 2      0.272 ± 0.0171   0.272   0.95 0.239   0.306 
#' 3 3      0.031 ± 0.0065   0.0308  0.95 0.0197  0.0450
#' 4 4      0.326 ± 0.0175   0.325   0.95 0.292   0.361 
#' 5 5      0.144 ± 0.0136   0.144   0.95 0.119   0.172


tidybayes::add_epred_rvars(
  newdata = data.frame(x = c(0, 1)),
  object = m
) |> 
  mutate(.epred = as.data.frame(.epred)) |> 
  unpack(.epred) |> 
  summarise(across(`1`:`5`, diff)) |> 
  pivot_longer(everything(), names_to = "group", values_to = ".epred") |> 
  mutate(median_ci(.epred))

#' # A tibble: 5 × 6
#'   group              .epred  estimate    CI   CI_low  CI_high
#'   <chr>          <rvar[1d]>     <dbl> <dbl>    <dbl>    <dbl>
#' 1 1      -0.13140 ± 0.02399 -0.131     0.95 -0.178   -0.0864 
#' 2 2      -0.05772 ± 0.01241 -0.0573    0.95 -0.0837  -0.0353 
#' 3 3       0.00071 ± 0.00095  0.000671  0.95 -0.00111  0.00277
#' 4 4       0.09684 ± 0.01879  0.0965    0.95  0.0618   0.136  
#' 5 5       0.09156 ± 0.01761  0.0910    0.95  0.0592   0.127

**Comment by vincentarelbundock** [comment] 2023-02-07 01:49
Thanks! Appreciate you taking the time, and sorry again for the bug.
