### ISSUE TITLE
Consistent syntax across `comparisons()` and `predictions()`

### ISSUE THREAD

**Issue by ngreifer** [vincentarelbundock/marginaleffects#393] opened 2022-06-27 16:28 UTC
Hi Vincent,

If I want the g-computation average marginal effect of a binary variable `treat`, I can run
```r
fit <- glm(y ~ treat * (x1 + x2), data = data, family = binomial)
comparisons(fit, newdata = data, variables = list(treat = 0:1)) |>
   summary()
```
However, if I want the marginal means that are being compared (i.e., the estimated average potential outcomes), the syntax is a lot more complicated, having to manually generate a counterfactual dataset in a seperate call:
```r
predictions(fit, newdata = datagrid(treat = 0:1, newdata = data, grid_type = "counterfactual")) |>
   summary(by = "treat")
```
To me it would seem natural to have the syntax be the same as the first block but replacing `comparisons` with `marginalmeans` or `predictions`. Is this a possibility (i.e., as an enhancement)? I saw one workaround was to supply `transform_pre = \(hi, lo) hi` and `transform_pre = \(hi, lo) lo` to `comparisons()`, which produces the same output. (Note that to get the ATT, you need `newdata = subset(data, treat == 1)` which is why I left that argument in.)

Thanks!

Noah

**Comment by vincentarelbundock** [comment] 2022-06-27 17:48
Interesting\!

``` r
library(marginaleffects)

set.seed(1024)
N <- 100
TF <- c(TRUE, FALSE)
data <- data.frame(
    y = sample(TF, N, replace = TRUE),
    treat = sample(TF, N, replace = TRUE),
    x1 = sample(TF, N, replace = TRUE),
    x2 = sample(TF, N, replace = TRUE))

fit <- glm(y ~ treat * (x1 + x2), data = data, family = binomial)
```

Currently these two commands are equivalent:

``` r
predictions(fit, variables = "treat")
#>   rowid     type predicted std.error  conf.low conf.high    y   x1    x2 treat
#> 1     1 response 0.4705882 0.1088218 0.2741053 0.6766298 TRUE TRUE FALSE  TRUE
#> 2     2 response 0.5474878 0.1197775 0.3192848 0.7573327 TRUE TRUE FALSE FALSE

predictions(fit, newdata = datagrid(treat = TF))
#>   rowid     type predicted std.error  conf.low conf.high   x1    x2 treat
#> 1     1 response 0.4705882 0.1088218 0.2741053 0.6766298 TRUE FALSE  TRUE
#> 2     2 response 0.5474878 0.1197775 0.3192848 0.7573327 TRUE FALSE FALSE
```

Is your feature request that these two commands should be equivalent?

``` r
predictions(fit, variables = list(treat = TF))

predictions(fit, newdata = datagrid(treat = TF, grid_type = "counterfactual"))
```

I like the fact that this would make the behavior more consistent with `comparisons()`. I’m not sure I love the fact that it would make the function behave in subtly different ways depending on whether `variables` is a vector or a list.

Open to arguments on either side.

**Comment by ngreifer** [comment] 2022-06-27 18:38
Basically, I guess I want a function with the exact same syntax as `comparisons()` that, instead of producing the average marginal effects, produces the average marginal means (i.e., the means compared in the average marginal effect).

For example, let's a user wants to compute the ATT (i.e., the average marginal effect among the treated). They fit their model, and then run
```r
comparisons(fit, variables = list(treat = TF), newdata = subset(data, treat == 1)) |>
  summary()
```
But now they want to know not just what the difference between the average marginal means is, but also what the average marginal means themselves are. Instead of using the same syntax, they have to write completely different syntax, which means that any adjustments they made to the original syntax to get the specific value they want (e.g., subsetting the data) need to be translated into the syntax for the new call. That is, the user has to run
```r
predictions(fit, newdata = datagrid(treat = TF, newdata = subset(data, treat == 1), grid_type = "counterfactual")) |>
  summary(by = "treat")
```
instead of a function like
```r
function_i_want(fit, variables = list(treat = TF), newdata = subset(data, treat == 1)) |>
  summary()
```
`marginalmeans()` can't seem to do this because it creates its own grid that crosses categorical variables instead of creating counterfactual datasets and doesn't accept `variables` as a named list. `predictions()` requires a totally different syntax even though the outputs should just be one step removed from the output of `comparisons()` (i.e., the average marginal effect is just the contrast between the average adjusted predictions). To me, the quantities I want are called the "average marginal means", which is why I originally thought that `marginalmeans()` does the work. I definitely don't think the syntax of `predictions()` needs to change, just that it would be nice if the same syntax a user learned to compute average marginal effects could also be used to compute average marginal means since these two quantities require the exact same inputs to compute and are conceptually and statistically highly related to each other.

**Comment by vincentarelbundock** [comment] 2022-06-28 02:16
Ok, I think I get it now. I was thrown off by the "average marginal means" expression, since we're not really marginalizing over anything, and you are using this in a [very different way than the `emmeans` package does](https://cran.r-project.org/web/packages/emmeans/vignettes/basics.html), which is what the `marginalmeans()` function was designed to emulate. I don't think I would use that terminology in the package, just to avoid confusion.

In terms of user interface, one option would be to add a new argument. Maybe something like:

```{r}
predictions(
    fit,
    variables = list(treat = TF), 
    newdata = subset(data, treat == 1),
    counterfactual = TRUE) |>
  summary()
```

It wouldn't be quite the same syntax as `comparisons()`, but perhaps it's close enough. 

Adding a new argument is less "costly" than adding a new function.

I feel like "counterfactual predictions" might an intuitive vocabulary to convey what you want to do.

Thoughts?

**Comment by ngreifer** [comment] 2022-06-28 03:49
Hi Vincent, you're right that average marginal means was the wrong term. I do think you are marginalizing over the observed distribution of the covariates in exactly the same way as average marginal effects do, but I agree that the term "average marginal means" has its own meaning, and I may be misunderstanding what "marginal" means.

The functionality I am trying to replicate is the Stata call `margins x`, where `x` is a predictor. Just that short call produces average predicted outcomes setting `x` to each of its levels and taking the average predicted outcome across the full dataset. The [Stata manual](https://www.stata.com/manuals/rmargins.pdf) calls these "predictive margins (potential outcome means)". These are the *default* output of `margins`, which is why I think it is a bit funny that it takes a lot of code and multiple function calls to produce it in `marginaleffects`.

I think the syntax you're proposing is a great solution. That way, the workflow to get predicted margins and their difference would be the following:

```r
predictions(
    fit,
    variables = list(treat = TF), 
    newdata = subset(data, treat == 1),
    counterfactual = TRUE) |>
  summary()

comparisons(
    fit,
    variables = list(treat = TF), 
    newdata = subset(data, treat == 1)) |>
  summary()
```

It's still a bit verbose compared to Stata, but it works and keeps the syntax consistent I think.

**Comment by vincentarelbundock** [comment] 2022-06-28 04:46
Great!

I think the issue is that "marginal" is used in two different things here. 

(1) "marginal means" means that we are averaging across rows/margins of a prediction grid. This is what the `emmeans` author uses that word for.

(2) I have always understood "marginal effects" to mean that we are looking at the effect of a marginal (or tiny) change in X on Y. Here "margins" is used in the sense of a derivative/slope.

This second point is also
why I don't like to talk about "marginal effects" when looking at the output of `comparisons()`. Except in rare cases, those are contrasts not derivatives.

I agree the `counterfactual` solution looks pretty good, but I need to think about it a bit. And I'll be on vacation for a couple weeks, so I'm not sure when ill get around to this. Will let you know.

**Comment by vincentarelbundock** [comment] 2022-06-28 04:50
And you are pointing to a 3rd meaning, when we are applying `summary()` to average over unit level estimates.

So yeah, no wonder everyone's confused...

**Comment by ngreifer** [comment] 2022-06-28 05:46
Enjoy your vacation! You deserve it!

**Comment by vincentarelbundock** [comment] 2022-07-21 14:10
Hey @ngreifer\!

I’m back from vacation and circling back to this.

Would it be enough to simply return the predicted values for each side of the contrast by default? For example, in the current Github version we have:

``` r
library(marginaleffects)

set.seed(1024)
N <- 100
TF <- c(TRUE, FALSE)
data <- data.frame(
    y = sample(TF, N, replace = TRUE),
    treat = sample(TF, N, replace = TRUE),
    x1 = sample(TF, N, replace = TRUE),
    x2 = sample(TF, N, replace = TRUE))

fit <- glm(y ~ treat * (x1 + x2), data = data, family = binomial)

cmp <- comparisons(
    fit,
    variables = "treat",
    newdata = subset(data, treat == TRUE))

head(cmp)
#>   rowid     type        term contrast_treat  comparison std.error
#> 1     1 response interaction   TRUE - FALSE -0.10589356 0.1731811
#> 2     2 response interaction   TRUE - FALSE -0.26683371 0.1750493
#> 3     3 response interaction   TRUE - FALSE -0.07689956 0.1618294
#> 4     4 response interaction   TRUE - FALSE -0.07689956 0.1618294
#> 5     5 response interaction   TRUE - FALSE -0.26683371 0.1750493
#> 6     6 response interaction   TRUE - FALSE -0.07689956 0.1618294
#>    statistic   p.value   conf.low  conf.high     y treat    x1    x2
#> 1 -0.6114614 0.5408942 -0.4453223 0.23353519  TRUE  TRUE FALSE  TRUE
#> 2 -1.5243349 0.1274251 -0.6099240 0.07625654 FALSE  TRUE FALSE FALSE
#> 3 -0.4751890 0.6346523 -0.3940794 0.24028029  TRUE  TRUE  TRUE FALSE
#> 4 -0.4751890 0.6346523 -0.3940794 0.24028029 FALSE  TRUE  TRUE FALSE
#> 5 -1.5243349 0.1274251 -0.6099240 0.07625654 FALSE  TRUE FALSE FALSE
#> 6 -0.4751890 0.6346523 -0.3940794 0.24028029 FALSE  TRUE  TRUE FALSE
#>   predicted_lo predicted_hi
#> 1    0.6058936    0.5000000
#> 2    0.6668337    0.4000000
#> 3    0.5474878    0.4705882
#> 4    0.5474878    0.4705882
#> 5    0.6668337    0.4000000
#> 6    0.5474878    0.4705882
```

**Comment by ngreifer** [comment] 2022-07-21 14:54
The `predicted_lo` and `predicted_hi` columns are nice, but what I'm hoping for is to be able to compute and perform inference on those values. Ideally, the output would look identical to the output of the call to `predictions()` in my first message. That is, what I'm hoping for already exists in the package, but requires a syntax quite far removed from the `comparisons()` syntax even though the prediction and averaging tasks are identical, differing only in whether the average predictions are displayed as-is or contrasted.

A user estimating a causal effect of a binary treatment wants two things:
1) The average adjusted counterfactual predictions in each treatment group
2) The contrast between the average adjusted counterfactual predictions, which is the average treatment effect

To get 1), we can use the `predictions()` syntax I mention in my first message. To get 2), we can use the `comparisons()` syntax I mention in my first message. The problem is that these syntaxes are very different, requiring different function calls within each call to the primary function, and requiring different arguments to be used, despite the fact that 1) and 2) involve the _exact same_ quantities (the average adjust counterfactual predictions), the only difference being whether they are produced as-is or contrasted with each other. If the `comparisons()` syntax provides enough information to compute the average adjusted counterfactual predictions and their contrast, it seems strange that that same syntax cannot be used in `predictions()` to get those quantities. Taking the means of `predicted_lo` and `predicted_hi` in the `comparisons()` output does compute the average adjusted predictions, but it does not provide inference (i.e., confidence intervals) for them.

**Comment by vincentarelbundock** [comment] 2022-07-21 15:08
Got it.

I guess I understood this all along, but was just lazy and trying to get away with something ;)

I'll think of something and ping you in the next few days when there's a solution.

**Comment by vincentarelbundock** [comment] 2022-07-23 00:30
I just pushed a commit which, I believe, resolves the issue in pretty much exactly the way you suggested.

Breaking change: The old `variables` behavior no longer works. We now accept only a named list, which creates counterfactual datasets in a way analogous to `comparisons()`. This is kind of dangerious if users include many variables or values in the `variables` argument, since the whole dataset gets duplicated, but I agree with your initial point that the behavior was not consistent across functions. This seems much better.

``` r
library(marginaleffects)
mod <- lm(mpg ~ am + hp, data = mtcars)

predictions(mod) |>
    nrow()
#> [1] 32

predictions(
    mod,
    variables = list(am = 0:1)) |>
    nrow()
#> [1] 64

predictions(
    mod,
    variables = list(am = 0:1),
    newdata = subset(mtcars, am == 1))
#>    rowid rowidcf     type predicted std.error statistic       p.value  conf.low conf.high  mpg  hp am
#> 1      1       1 response  20.10726 0.7754954 25.928271 3.197502e-148 18.521189 21.693322 21.0 110  0
#> 2      2       2 response  20.10726 0.7754954 25.928271 3.197502e-148 18.521189 21.693322 21.0 110  0
#> 3      3       3 response  21.10835 0.8513068 24.795229 1.009267e-135 19.367230 22.849466 22.8  93  0
#> 4      4       4 response  22.69832 0.9969624 22.767477 9.633317e-115 20.659302 24.737336 32.4  66  0
#> 5      5       5 response  23.52275 1.0811831 21.756489 5.996774e-105 21.311480 25.734016 30.4  52  0
#> 6      6       6 response  22.75721 1.0028126 22.693378 5.207977e-114 20.706224 24.808189 33.9  65  0
#> 7      7       7 response  22.69832 0.9969624 22.767477 9.633317e-115 20.659302 24.737336 27.3  66  0
#> 8      8       8 response  21.22612 0.8611495 24.648594 3.810136e-134 19.464875 22.987372 26.0  91  0
#> 9      9       9 response  19.93059 0.7637622 26.095284 4.123991e-150 18.368523 21.492661 30.4 113  0
#> 10    10      10 response  11.03853 1.0534342 10.478617  1.083156e-25  8.884019 13.193048 15.8 264  0
#> 11    11      11 response  16.27955 0.6773841 24.032965 1.258166e-127 14.894142 17.664954 19.7 175  0
#> 12    12      12 response   6.85750 1.5264978  4.492309  7.045510e-06  3.735461  9.979538 15.0 335  0
#> 13    13      13 response  20.16614 0.7795256 25.869763 1.458399e-147 18.571834 21.760452 21.4 109  0
#> 14    14       1 response  25.38434 0.8176495 31.045504 1.311940e-211 23.712060 27.056622 21.0 110  1
#> 15    15       2 response  25.38434 0.8176495 31.045504 1.311940e-211 23.712060 27.056622 21.0 110  1
#> 16    16       3 response  26.38543 0.8495566 31.057889 8.927432e-212 24.647895 28.122972 22.8  93  1
#> 17    17       4 response  27.97540 0.9378523 29.829221 1.633097e-195 26.057281 29.893527 32.4  66  1
#> 18    18       5 response  28.79983 0.9984147 28.845561 5.759979e-183 26.757846 30.841821 30.4  52  1
#> 19    19       6 response  28.03429 0.9418814 29.764142 1.137927e-194 26.107928 29.960656 33.9  65  1
#> 20    20       7 response  27.97540 0.9378523 29.829221 1.633097e-195 26.057281 29.893527 27.3  66  1
#> 21    21       8 response  26.50321 0.8546054 31.012219 3.689106e-211 24.755345 28.251073 26.0  91  1
#> 22    22       9 response  25.20768 0.8141664 30.961333 1.788209e-210 23.542520 26.872835 30.4 113  1
#> 23    23      10 response  16.31562 1.3461861 12.119883  8.287707e-34 13.562359 19.068879 15.8 264  1
#> 24    24      11 response  21.55663 0.8911611 24.189380 2.877797e-129 19.734004 23.379263 19.7 175  1
#> 25    25      12 response  12.13458 1.8236238  6.654105  2.850282e-11  8.404856 15.864314 15.0 335  1
#> 26    26      13 response  25.44323 0.8189580 31.067807 6.558334e-212 23.768271 27.118186 21.4 109  1
```

**Comment by vincentarelbundock** [comment] 2022-07-25 01:40
Closing this to clean up the repo, but feel free to keep the discussion going or open a new issue if appropriate.

**Comment by ngreifer** [comment] 2022-10-21 16:04
Just wanted to bring up something that I found when I made my pull request yesterday. You currently have it so that `predictions()` requires a named list for the `variables` argument, whereas `comparisons()` doesn't require this and allows simply the name of the predictor of interest. In `predictions()`, this is controlled by a function that checks to make sure the input is a list. But when I removed that check and supplied the name of the predictor to `variables`, I got the answer I was looking for, which is the same as setting `variables = list(varname = unique(data$varname))`. So, I'm wondering why you wanted to prevent this form of input given that you allow it for `comparisons()`. You can test this difference by just commenting out this line in `predictions()`: https://github.com/vincentarelbundock/marginaleffects/blob/b46ce145ac9326284531b4b7911d07893378e3a9/R/predictions.R#L230
I thought about making a pull request for this, but I was wondering if maybe you denied this option for a special reason. It would improve the consistency between `comparisons()` and `predictions()`, which is a virtue IMO.

**Comment by vincentarelbundock** [comment] 2022-10-21 16:11
Right. So the two `variables` argument are already quite inconsistent because they do different things:

* `comparisons`: specify the contrast we want to look at
* `predictions()`: make counterfactual predictions by duplicating the whole dataset for each of the combinations given in `variables`

The first one is pretty "safe". If the user just supplies a variable name, then we get the default contrast, which is typically cheap to compute.

However, defaulting to `unique` if users supply just a variable name in `variables` could blow things up really easily if the dataset is large and there are many unique values. So I thought it best to force users to be more explicit as a safety precaution, because mysterious hanging processes are very bad. But maybe there are smart checks and warning we could implement.

**Comment by vincentarelbundock** [comment] 2022-10-21 18:04
That all sounds reasonable. Continous could be `fivenum()` by default. That's what we use in `plot_cap` already.

Probably best to open a new issue for this as well, otherwise it might get lost in this "dead" conversation.

**Comment by vincentarelbundock** [comment] 2022-10-21 18:04
Also probably should include a check on the max number of factor levels, which can be very high.

**Comment by ngreifer** [comment] 2022-10-25 20:04
Just wanted to highlight someone else confusing the terms "average marginal means" with "adjusted predictions": https://stats.stackexchange.com/q/592518/116195

As usual, the answer was one of the great functions in `marginaleffects`!

**Comment by vincentarelbundock** [comment] 2022-10-25 21:12
This is very cool, thanks so much!

I'll reopen temporarily because I'd like to track and link to relevant posts and stats/stack answers.

BTW, not sure if you've tried this, but `datagrid()` should accept functions so you could potentially do `datagrid(Species = unique)`

(Just plugging this because I think it's a neat trick)

**Comment by ngreifer** [comment] 2022-10-25 21:22
That is a cool trick!

`marginaleffects` is the solution to many of my problems, so I want it to work as well for my purposes as possible, which is why I've been so involved in its improvement. I don't think I've ever felt so excited about a package that isn't mine.

**Comment by vincentarelbundock** [comment] 2022-10-25 21:32
Nice! I really do appreciate all your feature requests, examples, and code submissions.

Frankly, I have to say that I'm kind of surprised about where this all ended up. Just a confluence of (a) being on sabbatical and able to invest ridiculous hours, and (b) lucking my way into a surprisingly flexible infrastructure. I wish I could say there was a grand design, but...

**Comment by vincentarelbundock** [comment] 2022-10-25 21:41
I watch too much "Grand Design" with Kevin McCloud.

**Closed** 2022-10-26 23:53 UTC
