### ISSUE TITLE
Confidence intervals missing in plot_cap() of binomial logistic models with weights

### ISSUE THREAD

**Issue by fschaffner** [vincentarelbundock/marginaleffects#230] opened 2022-03-24 10:57 UTC
Hi @vincentarelbundock,

I noticed that the confidence intervals in `plot_cap()` are not being plotted in binomial logistic regression models that include weights. 

``` r
library("marginaleffects")

# Model without weights => The confidence intervals get plotted
no_weights <- glm(
  am ~ mpg * cyl, 
  data = mtcars,
  family = binomial(link = "logit")
)

no_weights |> plot_cap(condition = c("mpg", "cyl"))
```

![](https://i.imgur.com/yNsDKdG.png)

``` r

# Model with weights => The confidence intervals are missing
with_weights <- glm(
  am ~ mpg * cyl, 
  data = mtcars,
  family = binomial(link = "logit"),
  weights = carb
)

with_weights |> plot_cap(condition = c("mpg", "cyl"))
```

![](https://i.imgur.com/uzVHq8P.png)

<sup>Created on 2022-03-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment] 2022-03-24 12:51
Thanks for the report\!

The issue is that `plot_cap()` uses `datagrid()` to construct the prediction grid, but `datagrid()` only knows to extract variables which appear in the model formula, and not those that appear in extra arguments. When, we then try to make predictions and confidence intervals, the call to `model.frame()` doesn’t work because the supplied data does not include the weights variable.

This could be fixed by a combination of a minor change in `marginaleffects` and an upstream fix in `insight`: <https://github.com/easystats/insight/issues/550>

In the meantime, you can construct a prediction grid manually with `datagrid`, taking care to specify the weights variable:

``` r
library(marginaleffects)
library(ggplot2)

mod <- glm(
    am ~ mpg * cyl,
    data = mtcars,
    family = binomial(link = "logit"),
    weights = carb)
nd <- datagrid(model = mod, cyl = mtcars$cyl, mpg = seq(10, 35, .1), carb = 1)
#> Warning in prep_datagrid(..., model = model, newdata = newdata): Some of the variable names are missing from the model data: carb

predictions(mod, newdata = nd) |>
    ggplot(aes(x = mpg, y = predicted, ymin = conf.low, ymax = conf.high)) +
    geom_ribbon(alpha = .1, aes(fill = factor(cyl))) +
    geom_line(aes(color = factor(cyl)))
```

![](https://i.imgur.com/JYIzq1v.png)

**Comment by vincentarelbundock** [comment] 2022-03-24 12:53
In the `insight` issue I discovered a new feature that will allow me to fix this without upstream changes. Will do it when I find a minute.

**Comment by vincentarelbundock** [comment] 2022-03-25 01:24
This should work with the development version:

``` r
library(marginaleffects)
mod <- glm(
    am ~ mpg * cyl,
    data = mtcars,
    family = binomial(link = "logit"),
    weights = carb)

plot_cap(mod, condition = c("mpg", "cyl"))
```

![](https://i.imgur.com/glgxQAB.png)

**Closed by vincentarelbundock** 2022-03-25 01:24 UTC

**Comment by fschaffner** [comment] 2022-03-25 10:41
Thanks a lot for the quick fix, I just tested it on my machine and it works perfectly!
