### ISSUE TITLE
Inconsistent estimates in some g-formula computations (glm models)

### ISSUE THREAD

**Issue by huftis** [vincentarelbundock/marginaleffects#865] opened 2023-08-10 18:52 UTC
I’m trying to do some g-formula computations following the [‘Causal Inference’ chapter](https://vincentarelbundock.github.io/marginaleffects/articles/gformula.html) in the `marginaleffects` documentation. I’m not 100% sure, but the following feels like a bug.

To my mind, the following two commands should give the *exact same* results:

```r
avg_comparisons(mod, variables = list(foo = 0:1),
                type = "response", comparison = "difference")
comparisons(mod, variables = list(foo = 0:1),
            type = "response", comparison = "differenceavg")
```

My reasoning is: I have `type = "response"`, so all values are on the response scale (e.g., for a binomial regression model, on the probability scale). There should be no transformations or back-transformations than can influence things. And the first command calculates the average of differences, while the second calculates the difference in averages. The two results should therefore be identical.

The two results are actually *often* identical – but sometimes (for some datasets/models) not.

I have managed to come up with a *relatively* simple example where the results differ:
  
```r
library(marginaleffects)
d = data.frame(
  outcome = c(0,0,1,0,0,1,1,1,0,0,0,1,0,1,0,
              0,0,0,0,1,0,0,1,1,1,0,0,0,1,0,0,0,0,0,0,0,
              0,1,0,1,0,0,1,1,0,1,0,1,0,0,1,0,1,0,1,0,1,
              1,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,1,0,1,1,1,
              0,0,0,0,1,1,0,0,1,0,1,0,1,0,1,0,1,0,0,1,1,0),
  foo = c(1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,
          1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,
          1,1,1,1,0,1,1,1,1,1,0,1,1,1,1,0,1,1,1,1,1,
          1,1,0,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,
          1,1,0,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1),
  bar = c(1,1,1,0,0,0,1,1,0,0,1,0,1,0,1,
          1,1,1,0,1,1,1,1,0,1,0,0,1,0,0,1,1,1,1,0,0,
          1,1,0,1,1,1,1,1,0,1,1,1,1,0,1,0,0,0,0,0,1,
          1,0,0,0,0,1,0,1,1,0,0,1,1,1,1,1,1,1,1,0,1,
          0,1,1,0,1,0,1,1,1,0,1,0,1,1,0,0,1,1,0,1,1,1)
)
mod = glm(
  outcome ~ foo + bar,
  family = "binomial",
  data = d
)
```

I get the following results:

``` r
avg_comparisons(mod, variables = list(foo = 0:1),
                type = "response", comparison = "difference")
#> 
#>  Term Contrast Estimate Std. Error    z Pr(>|z|)    S 2.5 % 97.5 %
#>   foo    1 - 0    0.361     0.0988 3.65   <0.001 11.9 0.167  0.554
#> 
#> Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
comparisons(mod, variables = list(foo = 0:1),
            type = "response", comparison = "differenceavg")
#> 
#>  Term          Contrast Estimate Std. Error   z Pr(>|z|)    S 2.5 % 97.5 %
#>   foo mean(1) - mean(0)    0.344     0.0931 3.7   <0.001 12.2 0.162  0.527
#> 
#> Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted, predicted_hi, predicted_lo
```

That is, the first method gives the estimate 0.361 (or 0.3606065 if we include a few more decimals), while the second gives the estimate 0.344.

I believe only the first one is correct. If I do the calculations manually, I get identical results (0.361) for both ways of calculating the estimate:

``` r
d0 = d; d0$foo = 0
d1 = d; d1$foo = 1
ps0 = predict(mod, newdata = d0, type = "response")
ps1 = predict(mod, newdata = d1, type = "response")
p0 = mean(ps0)
p1 = mean(ps1)
# Expected results
mean(ps1 - ps0) # mean pairwise difference
#> [1] 0.3606065
p1 - p0 # difference in means
#> [1] 0.3606065
```

Also note that if I use `type = "link"`, the estimates for the two methods *are* identical:

``` r
avg_comparisons(mod, variables = list(foo = 0:1),
                type = "link", comparison = "difference")
#> 
#>  Term Contrast Estimate Std. Error    z Pr(>|z|)   S  2.5 % 97.5 %
#>   foo    1 - 0     2.19       1.09 2.01    0.044 4.5 0.0587   4.32
#> 
#> Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
comparisons(mod, variables = list(foo = 0:1),
            type = "link", comparison = "differenceavg")
#> 
#>  Term          Contrast Estimate Std. Error    z Pr(>|z|)   S  2.5 % 97.5 %
#>   foo mean(1) - mean(0)     2.19       1.09 2.01    0.044 4.5 0.0587   4.32
#> 
#> Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted, predicted_hi, predicted_lo
```

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

```r
R version 4.3.1 (2023-06-16)
Platform: x86_64-suse-linux-gnu (64-bit)
Running under: openSUSE Tumbleweed

Matrix products: default
BLAS:   /usr/lib64/R/lib/libRblas.so 
LAPACK: /usr/lib64/R/lib/libRlapack.so;  LAPACK version 3.11.0

locale:
 [1] LC_CTYPE=nn_NO.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=nn_NO.UTF-8        LC_COLLATE=nn_NO.UTF-8    
 [5] LC_MONETARY=nn_NO.UTF-8    LC_MESSAGES=nn_NO.UTF-8   
 [7] LC_PAPER=nn_NO.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=nn_NO.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Oslo
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] marginaleffects_0.13.0.9014

loaded via a namespace (and not attached):
[1] compiler_4.3.1    generics_0.1.3    tools_4.3.1       rstudioapi_0.14  
[5] Rcpp_1.0.11       data.table_1.14.8
```
</details>

**Comment by vincentarelbundock** [comment] 2023-08-13 20:49
Yep, this is a bug. I really appreciate the detailed description and reproducible example. Thanks\!

Should be fixed on Github now, and I will release to CRAN in the next few days.

Note to self so I remember in the future: the problem was that when the predictors are all binary or categorical, we only make predictions on a deduplicated dataset, and then we use weights to compute the average. But `dedup_newdata()` was called after `sanitize_variables()`, so the `wts` string was never tacked onto the `comparison` string that determines which aggregation function is used. So we only got `differenceavg` rather than `differenceavgwts`.

``` r
library(marginaleffects)
d = data.frame(
  outcome = c(0,0,1,0,0,1,1,1,0,0,0,1,0,1,0,
              0,0,0,0,1,0,0,1,1,1,0,0,0,1,0,0,0,0,0,0,0,
              0,1,0,1,0,0,1,1,0,1,0,1,0,0,1,0,1,0,1,0,1,
              1,1,0,0,0,0,0,0,0,1,0,1,0,1,1,1,1,0,1,1,1,
              0,0,0,0,1,1,0,0,1,0,1,0,1,0,1,0,1,0,0,1,1,0),
  foo = c(1,1,1,1,1,1,0,1,1,1,1,1,1,1,0,
          1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,
          1,1,1,1,0,1,1,1,1,1,0,1,1,1,1,0,1,1,1,1,1,
          1,1,0,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,
          1,1,0,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1),
  bar = c(1,1,1,0,0,0,1,1,0,0,1,0,1,0,1,
          1,1,1,0,1,1,1,1,0,1,0,0,1,0,0,1,1,1,1,0,0,
          1,1,0,1,1,1,1,1,0,1,1,1,1,0,1,0,0,0,0,0,1,
          1,0,0,0,0,1,0,1,1,0,0,1,1,1,1,1,1,1,1,0,1,
          0,1,1,0,1,0,1,1,1,0,1,0,1,1,0,0,1,1,0,1,1,1)
)
mod = glm(
  outcome ~ foo + bar,
  family = "binomial",
  data = d
)

# response
avg_comparisons(mod, variables = list(foo = 0:1),
    type = "response", comparison = "difference")
# 
#  Term Contrast Estimate Std. Error    z Pr(>|z|)    S 2.5 % 97.5 %
#   foo    1 - 0    0.361     0.0988 3.65   <0.001 11.9 0.167  0.554
# 
# Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
comparisons(mod, variables = list(foo = 0:1),
    type = "response", comparison = "differenceavg")
# 
#  Term          Contrast Estimate Std. Error    z Pr(>|z|)    S 2.5 % 97.5 %
#   foo mean(1) - mean(0)    0.361     0.0988 3.65   <0.001 11.9 0.167  0.554
# 
# Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted

# link
avg_comparisons(mod, variables = list(foo = 0:1),
    type = "link", comparison = "difference")
# 
#  Term Contrast Estimate Std. Error    z Pr(>|z|)   S  2.5 % 97.5 %
#   foo    1 - 0     2.19       1.09 2.01    0.044 4.5 0.0587   4.32
# 
# Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high
comparisons(mod, variables = list(foo = 0:1),
    type = "link", comparison = "differenceavg")
# 
#  Term          Contrast Estimate Std. Error    z Pr(>|z|)   S  2.5 % 97.5 %
#   foo mean(1) - mean(0)     2.19       1.09 2.01    0.044 4.5 0.0587   4.32
# 
# Columns: term, contrast, estimate, std.error, statistic, p.value, s.value, conf.low, conf.high, predicted_lo, predicted_hi, predicted
```

**Closed by vincentarelbundock** 2023-08-13 20:49 UTC
