### ISSUE TITLE
Delta method standard error for average adjusted predictions

### ISSUE THREAD

**Issue by ray-p144** [vincentarelbundock/marginaleffects#332] opened 2022-05-21 23:17 UTC
Would it be possible to use the delta method to calculate the standard error in `tidy.predictions()` like it is for `tidy.comparisons()`?

I was trying to use the `marginaleffects` package to reproduce the [`margins a` command in Stata](https://www.stata.com/manuals/rmargins.pdf) for the average adjusted predictions (listed as "Predictive margins (potential-outcome means)" in the Stata documentation). When only fitting a univariable model and using the method provided in the [vignette](https://github.com/vincentarelbundock/marginaleffects/blob/bf3e5618308ed556ac6f092d8988b80bea50757a/vignettes/mfx01_predictions.Rmd#L162-L164), the standard errors match those from Stata; however, this seems to be because the standard errors calculated in `predictions()` are the same for all the observations at each level of the one predictor. This breaks down when a multivariable model is used.

I can "trick" the `comparisons()` function to provide the results that match the `margins a` command in Stata (the standard errors are slightly different after 3 or 4 significant digits) by having the function passed to `transform_pre` simply return `hi` and `lo` separately, but I was wondering if it would be better to incorporate the functionality into the `tidy.predictions()` function rather than using `comparisons()` function as a work-around.

### Stata
``` stata
. import delimited "https://vincentarelbundock.github.io/Rdatasets/csv/datasets/mtcars.csv", clear
(encoding automatically selected: ISO-8859-1)
(12 vars, 32 obs)

. drop v1

. 
. egen cyl0 = group(cyl)

. recode am (0 = 1 automatic) (1 = 2 manual), generate(am0)
(32 differences between am and am0)

. drop cyl am

. rename cyl0 cyl

. rename am0 am
```

### R
``` r
library(data.table)
library(marginaleffects)
#> Warning: package 'marginaleffects' was built under R version 4.1.3
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:data.table':
#> 
#>     between, first, last
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
options(pillar.sigfig = 7)

dt <- as.data.table(mtcars)
dt[, am := factor(am)]
```

### Stata
``` stata
. 
. quietly logistic vs i.am

. margins am

Adjusted predictions                                        Number of obs = 32
Model VCE: OIM

Expression: Pr(vs), predict()

------------------------------------------------------------------------------
             |            Delta-method
             |     Margin   std. err.      z    P>|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
          am |
  automatic  |   .3684211   .1106647     3.33   0.001     .1515222    .5853199
     manual  |   .5384615   .1382642     3.89   0.000     .2674688    .8094543
------------------------------------------------------------------------------
```

### R (vignette method)
Same point estimates and standard errors
``` r
mod <- glm(vs ~ am, data = dt, family = binomial)
predictions(mod, newdata = datagrid(am = 0:1, grid_type = "counterfactual")) %>%
    group_by(am) %>%
    summarize(across(c(predicted, std.error), mean))
#> # A tibble: 2 x 3
#>   am    predicted std.error
#>   <fct>     <dbl>     <dbl>
#> 1 0     0.3684211 0.1106647
#> 2 1     0.5384615 0.1382642
```

## Stata
``` stata
. 
. quietly logistic vs hp i.am

. margins am

Predictive margins                                          Number of obs = 32
Model VCE: OIM

Expression: Pr(vs), predict()

------------------------------------------------------------------------------
             |            Delta-method
             |     Margin   std. err.      z    P>|z|     [95% conf. interval]
-------------+----------------------------------------------------------------
          am |
  automatic  |   .5261185   .0330363    15.93   0.000     .4613686    .5908684
     manual  |   .3301815   .0646091     5.11   0.000       .20355     .456813
------------------------------------------------------------------------------
```

### R (vignette method)
Same point estimates. Different standard errors.
``` r
mod <- glm(vs ~ hp + am, data = dt, family = binomial)
predictions(mod, newdata = datagrid(am = 0:1, grid_type = "counterfactual")) %>%
    group_by(am) %>%
    summarize(across(c(predicted, std.error), mean))
#> # A tibble: 2 x 3
#>   am    predicted  std.error
#>   <fct>     <dbl>      <dbl>
#> 1 0     0.5261185 0.04275179
#> 2 1     0.3301815 0.07396842


```

### R `comparisons()` work-around
Same point estimates and standard errors as Stata (only up to 3 or 4 significant digits for standard errors).
``` r
comparisons(mod, variables = "am",
            transform_pre = function(hi, lo) { return(lo) }) %>%
    tidy(.)
#>       type term contrast  estimate  std.error statistic p.value  conf.low
#> 1 response   am     1, 0 0.5261185 0.03302867  15.92915       0 0.4613835
#>   conf.high
#> 1 0.5908535
comparisons(mod, variables = "am",
            transform_pre = function(hi, lo) { return(hi) }) %>%
    tidy(.)
#>       type term contrast  estimate  std.error statistic      p.value  conf.low
#> 1 response   am     1, 0 0.3301815 0.06461896  5.109669 3.227235e-07 0.2035307
#>   conf.high
#> 1 0.4568324
```

## Weighted survey data
I have mostly been working with survey data, but since the work-around I am using above also breaks down since it is not able to incorporate the weights, I also included the work-around I am currently using to incorporate the weights. (I saw that you opened an issue regarding weights (#327), but I wasn't completely sure it was related to this. But if you need any other weighted results from Stata, I can help with that.)

### Stata
Using `nhanes` data from the `survey` package.
``` stata
. import delimited "...\nhanes.csv", clear
(encoding automatically selected: ISO-8859-1)
(7 vars, 8,591 obs)

. 
. encode agecat, generate(agecat0)

. drop agecat

. rename agecat0 agecat

. 
. svyset sdmvpsu [pweight=wtmec2yr] , strata(sdmvstra)

Sampling weights: wtmec2yr
             VCE: linearized
     Single unit: missing
        Strata 1: sdmvstra
 Sampling unit 1: sdmvpsu
           FPC 1: <zero>

. 
. quietly svy: logistic hi_chol i.riagendr i.agecat

. margins riagendr

Predictive margins

Number of strata = 15                            Number of obs   =       7,846
Number of PSUs   = 31                            Population size = 255,345,910
Model VCE: Linearized                            Design df       =          16

Expression: Pr(hi_chol), predict()

------------------------------------------------------------------------------
             |            Delta-method
             |     Margin   std. err.      t    P>|t|     [95% conf. interval]
-------------+----------------------------------------------------------------
    riagendr |
          1  |   .1020398   .0076131    13.40   0.000     .0859007    .1181789
          2  |   .1215787   .0062657    19.40   0.000      .108296    .1348614
------------------------------------------------------------------------------

```

### R
``` r
library(data.table)
library(marginaleffects)
#> Warning: package 'marginaleffects' was built under R version 4.1.3
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:data.table':
#> 
#>     between, first, last
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(survey)
#> Loading required package: grid
#> Loading required package: Matrix
#> Loading required package: survival
#> 
#> Attaching package: 'survey'
#> The following object is masked from 'package:graphics':
#> 
#>     dotchart

data(nhanes)
setDT(nhanes)
nhanes[, RIAGENDR := factor(RIAGENDR, labels = c("male", "female"))]

svydsgn <- svydesign(id = ~SDMVPSU, strata = ~SDMVSTRA, weights = ~WTMEC2YR, nest = TRUE, data = nhanes)
svymod <- svyglm(HI_CHOL ~ RIAGENDR + agecat, design = svydsgn, family = binomial)
#> Warning in eval(family$initialize): non-integer #successes in a binomial glm!

```
#### Vignette method
Incorrect (unweighted) point estimates and standard errors.
``` r
predictions(svymod, newdata = datagrid(RIAGENDR = c("male", "female"), grid_type = "counterfactual")) %>%
    group_by(RIAGENDR) %>%
    summarize(across(c(predicted, std.error), mean))
#> # A tibble: 2 x 3
#>   RIAGENDR predicted std.error
#>   <fct>        <dbl>     <dbl>
#> 1 male        0.0929   0.00954
#> 2 female      0.111    0.00927
```

#### Unweighted `comparisons()` work-around
No change in point estimates using previous work-around.
``` r
comparisons(svymod, variables = "RIAGENDR",
            transform_pre = function(hi, lo) { return(lo) }) %>%
    tidy(.)
#>       type     term     contrast   estimate   std.error statistic p.value
#> 1 response RIAGENDR female, male 0.09293246 0.006825716  13.61505       0
#>    conf.low conf.high
#> 1 0.0795543 0.1063106
comparisons(svymod, variables = "RIAGENDR",
            transform_pre = function(hi, lo) { return(hi) }) %>%
    tidy(.)
#>       type     term     contrast  estimate   std.error statistic p.value
#> 1 response RIAGENDR female, male 0.1107585 0.005807376  19.07204       0
#>     conf.low conf.high
#> 1 0.09937625 0.1221407
```

#### Weighted `comparisons()` work-around
New work-around using `weighted.mean()` in the function passed to `transform_pre` provides the same point estimates and standard errors as Stata (only up to 3 or 4 significant digits for the standard errors).
``` r
comparisons(svymod, variables = "RIAGENDR",
            transform_pre = function(hi, lo) { return(weighted.mean(lo, w = svymod$prior.weights)) }) %>%
    tidy(.)
#>       type     term     contrast  estimate   std.error statistic p.value
#> 1 response RIAGENDR female, male 0.1020398 0.007613427  13.40261       0
#>     conf.low conf.high
#> 1 0.08711776 0.1169618
comparisons(svymod, variables = "RIAGENDR",
            transform_pre = function(hi, lo) { return(weighted.mean(hi, w = svymod$prior.weights)) }) %>%
    tidy(.)
#>       type     term     contrast  estimate   std.error statistic p.value
#> 1 response RIAGENDR female, male 0.1215787 0.006265914  19.40319       0
#>    conf.low conf.high
#> 1 0.1092977 0.1338597
```

<sup>Created on 2022-05-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ray-p144** [comment] 2022-05-21 23:30
I just saw that you added the `weights` argument to the `marginaleffects()` and `comparisons()` functions as I was typing this up. Haha.

**Comment by vincentarelbundock** [comment] 2022-05-21 23:53
> I just saw that you added the `weights` argument to the `marginaleffects()` and `comparisons()` functions as I was typing this up. Haha.

Ha, yeah!

If you have a chance, could you compare a couple models in Stata. I don't have access to a local copy, and couldn't figure out exactly what kind of "robust" vce
they are using by default in weighted models.

Will give a complete answer on average predictions later, but the short is: very tricky (for package reasons, not math-y ones).

**Comment by vincentarelbundock** [comment] 2022-05-22 20:11
Here’s the problem with average predictions.

All other quantities produced by the package (`marginaleffects`, `comparisons`, and `marginalmeans`) are computed pretty entirely by `marginaleffects`. However, the output of `predictions()` is often outsourced to `insight::get_predicted()`.

The benefit of this is that `insight` offers some nice features for many models:

1.  Predictions are first made on the link scale, and then backtransformed. This prevents weird confidence intervals, such as outside \[0,1\] in logistic regression.
2.  It has some nice features and guardrails for random effects models.

Those are really nice features, and I don’t think we should scrap them to just return the delta method SEs on the “final” scale, where CIs don’t always make sense.

I just pushed a few commits on the “infrastructure” side, and we can now do this, but only for `lm()` or `glm()` models on the link scale:

``` r
library(marginaleffects)

mod1 <- lm(am ~ mpg + factor(cyl), data = mtcars)

mod2 <- glm(am ~ mpg + factor(cyl), data = mtcars, family = binomial)

predictions(mod1) |> summary()
#> Average Adjusted Predictions 
#>   Predicted Std. Error z value   Pr(>|z|)  2.5 % 97.5 %
#> 1    0.4063    0.07414   5.479 4.2734e-08 0.2609 0.5516
#> 
#> Model type:  lm 
#> Prediction type:  response

predictions(mod2, type = "link") |> summary(by = "cyl")
#> Average Adjusted Predictions 
#>   cyl Predicted Std. Error z value Pr(>|z|)   2.5 %  97.5 %
#> 1   6   -0.3073     0.7866 -0.3906 0.696079 -1.8489  1.2344
#> 2   4    1.5213     0.9628  1.5801 0.114094 -0.3658  3.4084
#> 3   8   -2.0547     0.8418 -2.4409 0.014651 -3.7046 -0.4048
#> 
#> Model type:  glm 
#> Prediction type:  link
```

We can do this to get it back to the response scale, but it’s not super convenient:

``` r
predictions(mod2, type = "link") |>
    summary(by = "cyl",
            transform_post = insight::link_inverse(mod2))
#> Average Adjusted Predictions 
#>   cyl Predicted Pr(>|z|)   2.5 % 97.5 %
#> 1   6    0.4238 0.696079 0.13600 0.7746
#> 2   4    0.8207 0.114094 0.40956 0.9680
#> 3   8    0.1136 0.014651 0.02402 0.4002
#> 
#> Model type:  glm 
#> Prediction type:  link
```

To be more convenient, I’m afraid I would have to take “ownership” of all the backtransformation code, which would be *a lot* of work. Maybe that’s the solution, but I think I’ll take a bit of time to think about it before jumping in to this kind of project.

**Comment by ray-p144** [comment] 2022-05-23 05:08
That makes sense. I agree that preventing weird confidence intervals is important and can see the value in having additional features for random effects models.

I will play around with the new feature you added and let you know what I think (although it may take me some time to do any through testing, as I alluded to in my comment from the weights issue). I am not terribly opposed to just using the work-around with the `comparisons()` function whenever the delta method might be relevant if you end up finding that supporting this feature just for the `lm()` and `glm()` models is too much of a hassle.

**Comment by vincentarelbundock** [comment] 2022-05-23 11:01
I'm hoping to find a solution for this, probably by on-boarding the calculation for a few models. We'll see...

WARNING: The `transform_post` in `summary()` is going to be deprecated immediately in the next release. I should have spent more time with this feature before releasing, because I find it too confusing. It will only be available in `comparisons()`, and the same transformation will be applied automatically in both stages.

**Comment by vincentarelbundock** [comment] 2022-05-23 19:24
After a bit of thought I decided to keep it in both `comparisons()` and `tidy()`. The issue, of course, is that taking the mean of a transform or the transform of a mean can yield very different results. I’m not sure what uses will want to do, so we should give both options:

``` r
x <- rnorm(100)
mean(exp(x))
#> [1] 1.881785
exp(mean(x))
#> [1] 1.083081
```

So I just decided to rename the one in `summary()`/`tidy()` to `transform_avg`

**Comment by vincentarelbundock** [comment] 2022-05-23 21:39
I think I have found a way to make this work for all models. The approach is flexible and easy to implement.

Unfortunately, it is somewhat wasteful in terms of computation and memory, and it doesn’t have the nice backtransform properties I described for the “usual” predictions.

With the latest from Github:

``` r
library(marginaleffects)

dat <- mtcars
dat$w <- 1:32
mod <- glm(am ~ hp + factor(cyl), data = dat, family = binomial)

p <- predictions(mod, weights = "w", newdata = dat)

summary(p, by = "am")
#> Average Adjusted Predictions 
#>   am Predicted Std. Error z value   Pr(>|z|) CI low CI high
#> 1  1    0.7166    0.09884   7.250 4.1601e-13 0.5229  0.9103
#> 2  0    0.2065    0.04976   4.151 3.3163e-05 0.1090  0.3041
#> 
#> Model type:  glm 
#> Prediction type:  response
```

**Comment by ray-p144** [comment] 2022-05-24 02:45
Awesome!

I just ran a few tests and it seems that using any name besides `w` for the weights column or passing a vector to it throws an error.

``` r
library(marginaleffects)

dat <- mtcars
dat$we <- 1:32
mod <- glm(am ~ hp + factor(cyl), data = dat, family = binomial)

p <- predictions(mod, weights = "we", newdata = dat)
summary(p, by = "am")
#> Error in weighted.mean.default(predicted, w, na.rm = TRUE): 'x' and 'w' must have the same length
p <- predictions(mod, weights = dat$we, newdata = dat)
summary(p, by = "am")
#> Error in weighted.mean.default(predicted, w, na.rm = TRUE): 'x' and 'w' must have the same length
```

<sup>Created on 2022-05-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


I looks like it worked in your example because the following two lines are actually pulling from the the column `w` in `x_dt` rather than the `w` object in the scope of the `tidy.predictions()` function.
https://github.com/vincentarelbundock/marginaleffects/blob/346d4adc959b10e8ed84561daff807b6c0d83c12/R/tidy.R#L157-L159

https://github.com/vincentarelbundock/marginaleffects/blob/346d4adc959b10e8ed84561daff807b6c0d83c12/R/tidy.R#L169-L171

**Comment by vincentarelbundock** [comment] 2022-05-24 12:26
Thanks for checking, I really appreciate it!

In principle, this should be fixed now.

**Closed by vincentarelbundock** 2022-05-24 12:26 UTC

**Comment by ray-p144** [comment] 2022-05-25 02:53
No problem!

It seems that it is still breaking for me though.
``` r
library(marginaleffects)
library(data.table)

dat <- mtcars
dat$we <- 1:32
mod <- glm(am ~ hp + factor(cyl), data = dat, family = binomial)

p <- predictions(mod, weights = "we", newdata = dat)
summary(p, by = "am")
#> Error in weighted.mean.default(predicted, ..w, na.rm = TRUE): 'x' and 'w' must have the same length

p <- predictions(mod, weights = dat$we, newdata = dat)
summary(p, by = "am")
#> Error in weighted.mean.default(predicted, ..w, na.rm = TRUE): 'x' and 'w' must have the same length
```

<sup>Created on 2022-05-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>


The issue is due to `..w` not being a column within the `data.table` so the entire vector is being passed to the `weighted.mean()` function for each group and `data.table` doesn't know to split it like it does with the `predictions` column.
``` r
foo <- function(x, w, ...) {
    message(sprintf("length(x) = %d; length(w) = %d", length(x), length(w)))
    return(NA)
}
as.data.table(p)[, foo(predicted, dat$we), by = am]
#> length(x) = 13; length(w) = 32
#> length(x) = 19; length(w) = 32
#>    am V1
#> 1:  1 NA
#> 2:  0 NA
```

Perhaps you had intended to do this? (Although `data.table` now considers this method [retired](https://rdatatable.gitlab.io/data.table/articles/datatable-programming.html#retired-interfaces) in favor of the new `env` argument, I don't know if you want force the newest version of `data.table` as a dependency.)
``` r
tidy_predictions <- function(x,
                             conf_level = 0.95,
                             by = NULL,
                             ...) {
    x_dt <- copy(data.table(x))
    
    w <- attr(x, "weights")
    ##### Debugging #####
    # if (!is.null(w)) w <- x[[w]]
    #####################
    
    by <- c("group", by)
    by <- intersect(by, colnames(x))
    if (length(by) == 0) by <- NULL
    
    fun <- function(...) {
        dots <- list(...)
        dots[["eps"]] <- NULL
        dots[["vcov"]] <- FALSE
        out <- data.table(do.call("predictions", dots))
        if (!is.null(w)) {
            out <- out[,
                       ##### Debugging #####
                       # .(estimate = stats::weighted.mean(predicted, ..w, na.rm = TRUE)),
                       .(estimate = stats::weighted.mean(predicted, get(w), na.rm = TRUE)),
                       #####################
                       by = by]
        } else {
            out <- out[,
                       .(estimate = mean(predicted)),
                       by = by]
        }
        return(out$estimate)
    }
    
    if (!is.null(w)) {
        x_dt <- x_dt[,
                     ##### Debugging #####
                     # .(estimate = stats::weighted.mean(predicted, ..w, na.rm = TRUE)),
                     .(estimate = stats::weighted.mean(predicted, get(w), na.rm = TRUE)),
                     #####################
                     by = by]
    } else {
        x_dt <- x_dt[,
                     .(estimate = mean(predicted)),
                     by = by]
    }
    
    se <- get_se_delta(
        model = attr(x, "model"),
        newdata = attr(x, "newdata"),
        vcov = attr(x, "vcov"),
        type = attr(x, "type"),
        FUN = fun,
        ...)
    
    if (!is.null(se)) {
        x_dt[, "std.error" := se]
    }
    
    out <- get_ci(x_dt, estimate = "estimate", conf_level = conf_level)
    return(out)
}
environment(tidy_predictions) <- asNamespace("marginaleffects")
assignInNamespace("tidy.predictions",
                  value = tidy_predictions,
                  ns = "marginaleffects")

summary(p, by = "am")
#> Average Adjusted Predictions 
#>   am Predicted Std. Error z value   Pr(>|z|) CI low CI high
#> 1  1    0.7166    0.09884   7.250 4.1601e-13 0.5229  0.9103
#> 2  0    0.2065    0.04976   4.151 3.3163e-05 0.1090  0.3041
#> 
#> Model type:  glm 
#> Prediction type:  response
```

<sup>Created on 2022-05-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by vincentarelbundock** [comment] 2022-05-25 11:50
Good catch.

Alright, attempt number 17. Hopefully it is fixed now.

BTW, I'm afraid I'll need to change the name of the `weights` argument. Sometimes it is convenient to push an argument forward to the `predict()` method of a model via the `...` dots. And some methods that we use like `pp_average` for bayesian model accept a useful argument named `weights`. So if we have our own `weights`, we can't push that one through.

`wts` would be less clear (I hate it), but perhaps that's the simple fix to this issue.

**Comment by ray-p144** [comment] 2022-05-25 12:51
Hmm... The dots do seem like an issue. I almost wonder if just creating an
argument like `predict_args` to take a list of arguments to pass
to`predict()` would be better, especially since different packages might
use different names for their nonstandard arguments.
