### ISSUE TITLE
Unable to compute adjusted predictions for model of class `brmsfit` when family is binomial

### ISSUE THREAD

**Issue by Dpananos** [vincentarelbundock/marginaleffects#500] opened 2022-09-28 21:26 UTC
Consider this minimal working example in which I simulate a binary outcome with multiple trials.

```r
library(tidyverse)
library(brms)
library(marginaleffects)


N <- 1250
n <- sample(10 : 100, size = N, replace = T)
x <- rbinom(N, 1, 0.5)
w <- rbinom(N, 1, 0.5)
z <- rbinom(N, 1, 0.5)
y <- rbinom(N, n, 0.25 + .25*x + .125*w + 0.05*z)
d <- tibble(x, w, z, y, n)


fit <- brm(
  y|trials(n) ~ .,
  data = d, 
  family = binomial(),
  backend = 'cmdstanr',
  chains = 10
)
```

I can plot the conditional adjusted prediction using `brms::conditional_effects`

```r
conditional_effects(fit, 'x')

Setting all 'trials' variables to 1 by default if not specified otherwise.
```
![image](https://user-images.githubusercontent.com/20362941/192891092-f10b55f8-7d2d-4112-a7c4-7c19e6c2615c.png)

However, when I do the same with `marginaleffects::plot_cap` I get the following error:

```r
plot_cap(fit, condition = 'x')

Error: 
Unable to compute adjusted predictions for model of class `brmsfit`. You can try to
specify a different value for the `newdata` argument. If this does not work and
you believe that this model class should be supported by `marginaleffects`,
please file a feature request on the Github issue tracker:

```

The error tells me to try a different value for `newdata`, but when I do that, I get the following error

```r
plot_cap(fit, condition = 'x', newdata=mutate(d, n=1))

Error in predictions(model, newdata = nd, type = type, vcov = vcov, conf_level = conf_level,  : 
  formal argument "newdata" matched by multiple actual arguments
```

However, I *can* get the adjusted predictions using `marginaleffects::predictions`

```r

predictions(
  fit,
  newdata = datagrid(x=0:1, z=0:1, w=0:1, n=1)
)

```

Is this intended functionality?  I've noticed this happens only when my `brms` model has `trials`.

**Comment by vincentarelbundock** [comment] 2022-09-29 00:56
Thanks for the report!

I think this should be fixed on Github. Make sure to restart after install.

For the record, the problems were:

1. `datagrid()` did not include the response, and `insight::find_variables()` considers that `n` is a "response" in formulas like `y|trials(n)`, so `n` got dropped from the data building process, and we couldn't make predictions anymore.
2. `datagrid()` was rounding the integers, but `posterior_epred` cannot make predictions when `datagrid()` fixes `n` to its mean with decimals rather than a round integer.

**Comment by vincentarelbundock** [comment] 2022-09-29 01:25
Checks won't pass because of a different bug caused by an upstream package.

**Closed** 2022-10-09 13:54 UTC
