### ISSUE TITLE
`plot_*()` improvements

### ISSUE THREAD

**Issue by grantmcdermott** [vincentarelbundock/marginaleffects#647] opened 2023-02-05 18:59 UTC
The cleaned up interface of the 0.9.0 release is fantastic. Among other things, I really like the consistency of the new `plot_*` functions.

However, one thing I wonder about is the fact that the arguments names for these `plot_*` functions are not consistent with their equivalent "main" functions. Consider the following slopes example:

``` r
library(marginaleffects)

mod = lm(mpg ~ wt * factor(am), data = mtcars)

slopes(mod, variables = "wt", by = "am")
#> 
#>  Term    Contrast Estimate Std. Error      z   Pr(>|z|)   2.5 % 97.5 % am
#>    wt mean(dY/dX)   -9.084     1.2124 -7.493 6.7421e-14 -11.461 -6.708  1
#>    wt mean(dY/dX)   -3.786     0.7856 -4.819 1.4440e-06  -5.326 -2.246  0
#> 
#> Prediction type:  response 
#> Columns: type, term, contrast, estimate, std.error, statistic, p.value, conf.low, conf.high, am, predicted, predicted_hi, predicted_lo

# Equivalent results in plot form
plot_slopes(mod, effect = "wt", condition = "am")
```

![](https://i.imgur.com/aUQk3gZ.png)

<sup>Created on 2023-02-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Here we need to change arguments when switching between the two function calls: `variables` becomes `effect` and `by` becomes `condition`. There might be some conceptual/technical blocker that I haven't thought about, but it would be nice if these arguments stayed the same. Then users could just switch out `slopes()` for `plot_slopes()` and everything else could pass through automatically.

```r
     slopes(mod, variables = "wt", by = "am")
plot_slopes(mod, variables = "wt", by = "am")
```

Maybe argument aliases are a way to go here?

**Comment by vincentarelbundock** [comment] 2023-02-05 20:53
To clarify, there are two different sets of quantities here:

1.  Your `slopes(by ...)` call marginalizes over the empirical distribution.
2.  The `plot_slopes()` code makes predictions on a grid of the predictors’ means.

In your simple `lm()` case they coincide, but this won’t always be true:

``` r
library(marginaleffects)
dat = transform(iris, big = Petal.Length > median(Petal.Length))
mod = glm(big ~ Sepal.Width * factor(Species) + Sepal.Length, data = dat, family = binomial)

# marginalizing across the EMPIRICAL DISTRIBUTION. `newdata=iris` was implicit in your code 
slopes(mod, variables = "Sepal.Width", newdata = dat, by = "Species")$estimate |> sort()
# [1] -2.636696e-09 -1.191077e-09  2.873916e-01

s = slopes(mod, variables = "Sepal.Width", newdata = dat)
aggregate(estimate ~ Species, FUN = mean, data = s)$estimate |> sort()
# [1] -2.636696e-09 -1.191077e-09  2.873916e-01

# no marginalizing: use a GRID OF SAMPLE AVERAGES
slopes(mod, variables = "Sepal.Width", newdata = datagrid(Species = unique))$estimate
# [1] -4.723199e-08  5.066321e-01 -1.283649e-08

plot_slopes(mod, effect = "Sepal.Width", condition = "Species", draw = FALSE)$estimate
# [1] -4.723199e-08  5.066321e-01 -1.283649e-08
```

I believe that the `plot_slopes()` behavior is the same as in `margins::cplot()` and as in most of the other packages which draw interaction plots, which is why I implemented it this way. I’m open to arguments about alternative approaches, but as long as they produce different numerical results, the different syntaxes might actually be a feature not a bug.

**Comment by grantmcdermott** [comment] 2023-02-12 01:31
> I’m open to arguments about alternative approaches, but as long as they produce different numerical results, the different syntaxes might actually be a feature not a bug.

For sure. But I think that this could be made clearer in the docs. (Apologies if it’s already there and I’m just missing it.) Your example is a good one, though as a user I can’t help but feel that a direct plot analogue of what slopes gives me would be nice.

+ 1 to all your desiderata above.

**Comment by vincentarelbundock** [comment] 2023-02-13 20:05
Closing issue to consolidate here: https://github.com/vincentarelbundock/marginaleffects/issues/673

**Closed by vincentarelbundock** 2023-02-13 20:05 UTC
