### ISSUE TITLE
Parallel computation?

### ISSUE THREAD

**Issue by bwiernik** [vincentarelbundock/marginaleffects#523] opened 2022-10-27 19:15 UTC
Is it possible to set `comparisons()` or `marginalmeans()` to compute with a parallel setup?

**Comment by vincentarelbundock** [comment] 2022-10-27 19:22
I made several attempts but never could get meaningful improvements, and often got significant slow downs. The problem is that 90% of computation is spent calling the `predict()` methods of individual packages: In general, `vcov` computation requires 2 calls to `predict()` per coefficient in the model. Those predict methods are often very slow, so a natural place to parallelize would be this loop:

https://github.com/vincentarelbundock/marginaleffects/blob/main/R/get_jacobian.R#L13

However, that loop calls a function that requires both a model object and a dataset (so, in effect, two datasets since model objects often store them too). When datasets are large, message passing to the nodes is very expensive. So when we most need parallelism, the parallelism overhead is a killer...

I'm interested in the problem so I'll probably revisit at some point, but it is not trivial.

**Comment by vincentarelbundock** [comment] 2022-10-27 19:24
`vcov=FALSE` typically speeds things up considerably.

**Comment by vincentarelbundock** [comment] 2022-11-01 11:45
I made another attempt and still couldn't get it. Closing now to keep the repo clean, but feel free to comment if you have ideas.

**Closed by vincentarelbundock** 2022-11-01 11:45 UTC
