### ISSUE TITLE
marginal effects with REndo package.

### ISSUE THREAD

**Issue by vikas16vk** [vincentarelbundock/marginaleffects#1056] opened 2024-03-25 00:58 UTC
I am using REndo package and copula correction command for multiple endogenous variable. Predict() command works with this package. I want to get the marginal effects after running the model. 

Make sure you are running the *latest development version* of `marginaleffects` and its dependencies: https://marginaleffects.com/#installation

**Comment by vincentarelbundock** [comment] 2024-03-28 02:22
Thanks a lot for the feature request @vikas16vk . I have implemented experimental support. I looks like it is working. However, I have no experience at all with this package.

Would you be able to try it and let me know if the results are accurate?

How would you suggest I check the numerical accuracy of the results? Is there another software out there we can compare to?

To install the feature branch:

```r
library(remotes)
install_github("vincentarelbundock/marginaleffects@issue1056")
```

**Comment by vincentarelbundock** [comment] 2024-04-06 11:16
I merged support for this in the main Github branch. Would still love it if you can test and give me some suggestions about how I could test the numerical accuracy of results.

**Closed by vincentarelbundock** 2024-04-06 11:16 UTC

**Comment by vikas16vk** [comment] 2024-04-06 12:38
Hello Vincent, Thanks for your reply.

I updated the  packages : 
library(remotes)
install_github("vincentarelbundock/marginaleffects@issue1056")

Then I run the model.
m_cop=   copulaCorecction()

prediction(m_cop)
slope(m_cop)

![Screenshot 2024-04-06 072921](https://github.com/vincentarelbundock/marginaleffects/assets/81926570/242cdc65-f16d-4b85-b4dd-c00ee0dfdf00)

Note : predict() works. I have interaction terms in the model and want to get marginal effects. 

Regarding other packages, In stata, I did not find copula correction method. If there is one, I am not aware about it>

**Comment by vincentarelbundock** [comment] 2024-04-06 12:46
please install the main branch, not the PR and then RESTART R completely for the change to take effect.

**Comment by vikas16vk** [comment] 2024-04-14 11:46
Thanks Vincent, The package works now. However, when I trying to get the marginal effects at mean with  slopes( mod, newdata="mean), it has problem.  The average_slope() works perfect. However, my research questions looks for effects at means.

I think datagrid function is unable to get the data from it. 
Could you please fix it. 


error: 
> slopes(m_cop, newdata = "mean")
Error: Unable to compute predicted values with this model. This error can arise when `insight::get_data()` is unable to extract the
  dataset from the model object, or when the data frame was modified since fitting the model. You can try to supply a different
  dataset to the `newdata` argument.
  
  Bug Tracker: https://github.com/vincentarelbundock/marginaleffects/issues

**Comment by vincentarelbundock** [comment] 2024-04-14 12:23
I cannot reproduce your problem on my computer. Please supply a minimal reproducible example, as described here: https://marginaleffects.com/vignettes/help.html#getting-help

**Comment by vikas16vk** [comment] 2024-04-14 13:43
![image](https://github.com/vincentarelbundock/marginaleffects/assets/81926570/42415990-17bc-4228-8b0e-aceae7f8c4ec)

would it helpful?

**Comment by vincentarelbundock** [comment] 2024-04-14 13:47
No this is not helpful. Please read the link I gave your.

**Comment by vikas16vk** [comment] 2024-04-14 13:47
One more thing. if that helps.

to install pacakge from github , I had to go to 4.2 version of R as 4.3 version was not supporting it. It may seems weird but i dont know what happened.

**Comment by vincentarelbundock** [comment] 2024-04-14 13:54
No, this is unrelated to the original problem and does not help me diagnose.

Also, your system sounds broken. The latest version of marginaleffects is tested on many versions of R.

**Comment by vikas16vk** [comment] 2024-04-15 03:59
Thanks Vincent, for your help. Its perfectly working now. I change the character variable to factors in the model. 

slopes(mod, newdata= "means" ) worked. 


However, I found both avg_slopes() and slopes() estimates are same.  I think they should be little different. I have about 12000 observations.

Any thought on that?
