### ISSUE TITLE
Error in `hypotheses()` when using `glmmTMB` model

### ISSUE THREAD

**Issue by reikookamoto** [vincentarelbundock/marginaleffects#1224] opened 2024-10-01 14:43 UTC
I get an error when using `hypotheses()` to test linear combinations of coefficients in a `glmmTMB` model. The error mentions an unused argument:

```
library(marginaleffects)
library(glmmTMB)

# Load example data
dat <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/causaldata/thornton_hiv.csv")

# Fit glmmTMB model
m <- glmmTMB(got ~ age * hiv2004 + (1 | villnum), data = dat)

# Hypotheses test
hypotheses(m, "b1 = b2")
#> Error in FUN(model = structure(list(obj = list(par = c(beta = 1, beta = 1, : unused argument (newparams = c(0.636679620757343, 0.00234719491200767, -0.0606009948792529, 0.000740363768876325, -0.815915595193961))
```
Even when I call `hypotheses()` without any arguments (it should return a data.frame of raw estimates), the same error occurs:

```
hypotheses(m)
#> Error in FUN(model = structure(list(obj = list(par = c(beta = 1, beta = 1, : unused argument (newparams = c(0.636679620757343, 0.00234719491200767, -0.0606009948792529, 0.000740363768876325, -0.815915595193961))
```

Could this be a bug in the way the function interacts with `glmmTMB` models? Thanks in advance for your help!

```
sessionInfo()
#> R version 4.4.1 (2024-06-14 ucrt)
#> Platform: x86_64-w64-mingw32/x64
#> Running under: Windows 11 x64 (build 22621)
#> 
#> Matrix products: default
#> 
#> 
#> locale:
#> [1] LC_COLLATE=English_Canada.utf8  LC_CTYPE=English_Canada.utf8   
#> [3] LC_MONETARY=English_Canada.utf8 LC_NUMERIC=C                   
#> [5] LC_TIME=English_Canada.utf8    
#> 
#> time zone: America/Toronto
#> tzcode source: internal
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] glmmTMB_1.1.10           marginaleffects_0.22.0.4
#> 
#> loaded via a namespace (and not attached):
#>  [1] Matrix_1.7-0        compiler_4.4.1      reprex_2.1.1       
#>  [4] Rcpp_1.0.13         splines_4.4.1       boot_1.3-31        
#>  [7] yaml_2.3.10         fastmap_1.2.0       coda_0.19-4.1      
#> [10] lattice_0.22-6      generics_0.1.3      knitr_1.48         
#> [13] backports_1.5.0     rbibutils_2.2.16    MASS_7.3-61        
#> [16] checkmate_2.3.2     nloptr_2.1.1        insight_0.20.4     
#> [19] minqa_1.2.8         TMB_1.9.15          rlang_1.1.4        
#> [22] xfun_0.47           fs_1.6.4            estimability_1.5.1 
#> [25] cli_3.6.3           withr_3.0.1         mgcv_1.9-1         
#> [28] Rdpack_2.6.1        emmeans_1.10.4      digest_0.6.37      
#> [31] grid_4.4.1          xtable_1.8-4        mvtnorm_1.3-1      
#> [34] rstudioapi_0.16.0   lme4_1.1-35.5       lifecycle_1.0.4    
#> [37] nlme_3.1-166        reformulas_0.3.0    evaluate_1.0.0     
#> [40] glue_1.7.0          data.table_1.16.0   numDeriv_2016.8-1.1
#> [43] rmarkdown_2.28      tools_4.4.1         htmltools_0.5.8.1
```

**Comment by vincentarelbundock** [comment] 2024-10-04 10:20
Thanks a lot for taking the time to investigate, @reikookamoto. I really appreciate it!

You hit on the right problem with ellipsis passing. The issue is that for all but one model, we compute standard errors by modifying the coefficients stored in a model object, and then by using that new model object to make (slightly different) predictions. The `glmmTMB` is the lone exception: We don't modify the object, but rather pass a `newparams` argument to the `predict()` function. Passing `...` through like you did solved that problem.

However, it did not solve all problems, since `hypotheses()` doesn't always need to call `predict()`. Sometimes, it just calls `coef()`. In those cases, I needed to overwrite the output with `newparams`.

Easy fix, but it would have taken me forever to figure out without the hints you provided. Thanks again!

I added a test, your name to the NEWS, and merged the fix to Github.

I expect a new official release to CRAN in the coming month. in the meantime, you can install the development version from Github with:

```{r}
remotes::install_github("vincentarelbundock/marginaleffects")
```

**Closed by vincentarelbundock** 2024-10-04 10:20 UTC

**Comment by reikookamoto** [comment] 2024-10-07 21:21
Hey, thanks so much for quickly tending to this issue! I tried installing the development version from GitHub and I can see the output is now a data.frame with non-NA values for `Std. Error`,  `z`, `Pr(>|z|)`,  `S`, `2.5 %` and `97.5 %`.

There's no rush on this, but for my own understanding, could you clarify what you mean by `hypotheses()` sometimes using `predict()` and other times using `coef()`? Is this related to how the standard errors are calculated for `glmmTMB`? Also, was the minimum reproducible example I shared above an instance where `coef()` was used instead of `predict()`...?

**Comment by vincentarelbundock** [comment] 2024-10-07 21:26
The difference is kind of hard to explain concisely, but it is completely uninteresting, having everything to do with software-related quirks, and absolutely nothing to do with numeric calculations or anything statistical.
