### ISSUE TITLE
fixest::i() not playing nice with marginaleffects

### ISSUE THREAD

**Issue by grantmcdermott** [vincentarelbundock/marginaleffects#484] opened 2022-09-08 05:46 UTC
I've been trying to nail down the root difficulty I'm having w.r.t. the marginaleffects for a **fixest** model that calls `i()` internally. I'm not sure that this MWE captures the exact problem I've been running into&mdash;the debugger appears to fail at a different point&mdash;but it's surprising enough that I wanted to quickly draw your attention to it.

``` r
library(fixest)
library(marginaleffects)

m = feols(Ozone ~ i(Month), airquality)
#> NOTE: 37 observations removed because of NA values (LHS: 37).
marginaleffects(m)
#> Error: Unable to compute adjusted predictions for this model. Either the
#>   `newdata` does not meet the requirements of the model's `predict()`
#>   method, or this model is not supported. If you believe this model should
#>   be supported, you can file a report on the Github Issue Tracker:
#>   https://github.com/vincentarelbundock/marginaleffects/issues

# predict works as expected
head(predict(m))
#> [1] 23.61538 23.61538 23.61538 23.61538 23.61538 23.61538

# FWIW the equivalent factor() version works as expected too...
m2 = feols(Ozone ~ factor(Month), airquality)
#> NOTE: 37 observations removed because of NA values (LHS: 37).
head(marginaleffects(m2), 3)
#> Warning: 
#> The `Month` variable is treated as a categorical (factor) variable, but the
#> original data is of class integer. It is safer and faster to convert such variables
#> to factor before fitting the model and calling `marginaleffects` functions.
#>  This warning appears once per session.
#>   rowid     type  term contrast    dydx std.error statistic   p.value conf.low
#> 1     1 response Month    6 - 5 5.82906  11.35618  0.513294 0.6077457 12.20427
#> 2     2 response Month    6 - 5 5.82906  11.35618  0.513294 0.6077457 12.20427
#> 3     3 response Month    6 - 5 5.82906  11.35618  0.513294 0.6077457 12.20427
#>   conf.high predicted predicted_hi predicted_lo Ozone Month
#> 1   35.0265  23.61538     29.44444     23.61538    41     5
#> 2   35.0265  23.61538     29.44444     23.61538    36     5
#> 3   35.0265  23.61538     29.44444     23.61538    12     5
```

<sup>Created on 2022-09-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Related: https://github.com/vincentarelbundock/marginaleffects/issues/136 (and https://github.com/lrberge/fixest/issues/235). Following the guidance in both threads, I'm using the latest development version of both **fixest** and **marginaleffects**.

``` r
sessionInfo()
#> R version 4.2.1 (2022-06-23)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Big Sur ... 10.16
#> 
#> Matrix products: default
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] marginaleffects_0.7.0.9001 fixest_0.10.4             
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.9          pillar_1.8.0        compiler_4.2.1     
#>  [4] dreamerr_1.2.3      highr_0.9           R.methodsS3_1.8.2  
#>  [7] R.utils_2.12.0      tools_4.2.1         digest_0.6.29      
#> [10] evaluate_0.16       lifecycle_1.0.1     tibble_3.1.8       
#> [13] nlme_3.1-159        R.cache_0.16.0      lattice_0.20-45    
#> [16] pkgconfig_2.0.3     rlang_1.0.4         reprex_2.0.2       
#> [19] cli_3.3.0           yaml_2.3.5          xfun_0.32          
#> [22] fastmap_1.1.0       withr_2.5.0         styler_1.7.0       
#> [25] stringr_1.4.0       knitr_1.39          generics_0.1.3     
#> [28] fs_1.5.2            vctrs_0.4.1         grid_4.2.1         
#> [31] data.table_1.14.3   glue_1.6.2          fansi_1.0.3        
#> [34] rmarkdown_2.15      Formula_1.2-4       purrr_0.3.4        
#> [37] magrittr_2.0.3      htmltools_0.5.3     numDeriv_2016.8-1.1
#> [40] sandwich_3.1-0      utf8_1.2.2          stringi_1.7.8      
#> [43] zoo_1.8-10          R.oo_1.25.0
```

**Comment by vincentarelbundock** [comment] 2022-09-08 11:52
The problem is that `marginaleffects` does not know about the `i()` function, and tried to take the derivative with respect to `Month` instead of treating it as a factor.

In such cases, it is safer to convert variables to factor in the original before fitting the model. This would remove ambiguity from `marginaleffects`'s perspective.

I committed a change to make your particular example work. However, it will only solve the problem for very simple cases with only one element/variable in the `i()` function. For more complicated cases, we would have to be able to parse the `i()` call to figure out what is a variable name and what is an argument, what variables are treatment as factors, and how to match variable names to their original name in the dataset (e.g., stripping the "i." prefix). Frankly, I don't know `fixest` enough to write such a parsing function. `i()` seems pretty complicated...

**Comment by grantmcdermott** [comment] 2022-09-08 18:45
Thanks mate. That latest commit solved the simple case as you suggested.

Following up on your point about more complicated cases, here's a better MWE of the issue I was originally running into.

``` r
library(fixest)
library(marginaleffects)

aq = airquality
aq$week = aq$Day %/% 7 + 1

## Simple i(f1) case works now...
# mod = feols(Ozone ~ i(Month), aq)
# marginaleffects(mod)

## ... but i(f1, i.f2) interaction case fails
mod2 = feols(Ozone ~ i(Month, i.week), aq)
#> NOTE: 37 observations removed because of NA values (LHS: 37).
marginaleffects(mod2)
#> Error in variable_class[[v]]: subscript out of bounds
```

<sup>Created on 2022-09-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The error occurs on lines 57--75 [here](https://github.com/vincentarelbundock/marginaleffects/blob/main/R/sanitize_variables.R#L57-L75) and arises b/c `insight::get_predictors()` doesn't parse the internal `i.` prefix on the second factor (here: `i.week`). Again, this is all stuff you already know but it hopefully helps to document.

OTOH, while `i()` is indeed fairly complicated on the internal side, it does have the "virtue" of being limited up to twoway interactions. (You can only do `i(f1)` or `i(f1, i.f2)`. You can't do `i(f1, i(f2, i.f3))`,  etc.) So a workaround could be as simple as checking whether the model object inherits from `fixest(_multi)` class and throw in an extra scrub for any "`i.`" prefixes returned by `insight::get_predictors()`. 

(The potential downside is scrubbing any regular variables that start with "i.", but I'm guessing that's an unlikely corner case. You can obvs add safety checks by parsing the model$fml return.) 

I've got to run, but will take stab at this later.

**Comment by vincentarelbundock** [comment] 2022-09-08 19:53
That all makes sense. Thanks for the extra info.

If we ever want to offer more complete support, I think the natural place to add an `if(inherits(model, "fixest")){...}` might be where we parse the terms here:

https://github.com/vincentarelbundock/marginaleffects/blob/main/R/find_categorical.R

**Comment by grantmcdermott** [comment] 2022-09-25 20:07
Finally getting around to tackling this. It looks like the error actually stems from `sanitize_newdata` over [here](https://github.com/vincentarelbundock/marginaleffects/blob/main/R/sanitize_newdata.R#L19). The current `insight::get_data(model)` approach doesn't seem to capture the full model frame (i.e., it drops any `i.xxx` variables). Simple example to demonstrate:

``` r
aq = airquality
aq$week = aq$Day %/% 7 + 1

model = fixest::feols(Ozone ~ i(Month, i.week), aq, notes = FALSE)

insight::get_data(model) |> head(2)
#>   Ozone Month
#> 1    41     5
#> 2    36     5
```

As you can see, the `get_data()` call drops the "week" column.

One workaround is to tack on any `i.` coef(s) manually. Something like this:

```r
idotcoefs = paste(model$fml[[3]])
idotcoefs = idotcoefs[grepl("i\\.", idotcoefs)]
idotcoefs = gsub(".*i\\.|\\)", "", idotcoefs)

newdata = insight::get_data(model)
newdata = cbind(newdata, eval(model$call$data)[, idotcoefs, drop = FALSE])

newdata |> head(2)
#>   Ozone Month week
#> 1    41     5    1
#> 2    36     5    1
```

What do you think: Is this something that you'd be okay with adding to the **marginaleffects** internels? Or would would you prefer to hand it off to the **parameters** upstream (i.e., a dedicated S3 `get_data` method for **fixest** objects)?

**Comment by vincentarelbundock** [comment] 2022-09-25 20:37
Hmm, yes, I think ideally this would be fixed upstream in `insight`. There is already a `get_data.fixest()` method here:

https://github.com/easystats/insight/blob/main/R/get_data.R#L784

If you go up the call stack, you find something like: 

`get_data.fixest()` -> `get_data_from_modelframe()` -> `find_variables()` -> `find_predictors()`.

So ultimately, if we fix the `find_predictors.fixest()` method, I expect that everything should work automatically. And if we fix this upstream, then other packages would benefit too. Here's the method that needs fixing (I think):

https://github.com/easystats/insight/blob/main/R/find_predictors.R#L148

**Comment by vincentarelbundock** [comment] 2022-09-26 01:39
I merged your PR into `insight` and made a small commit here. Things seem to work nicely now:

``` r
library(fixest)
library(marginaleffects)
library(modelsummary)

models <- list(
    feols(mpg ~ drat + i(cyl, i.gear), data = mtcars),
    feols(mpg ~ drat + i(cyl, gear), data = mtcars),
    feols(mpg ~ drat + i(cyl), data = mtcars),
    feols(mpg ~ drat + i(cyl, wt) + i(gear, i.am), data = mtcars)
)

models <- lapply(models, marginaleffects)

modelsummary(
    models,
    shape = term + contrast ~ model,
    output = "markdown")
```

|          |       | Model 1 | Model 2 | Model 3  | Model 4 |
| :------- | :---- | :-----: | :-----: | :------: | :-----: |
| drat     | dY/dX |  2.694  |  1.941  |  1.793   | \-0.135 |
|          |       | (2.322) | (1.785) | (1.509)  | (2.040) |
| cyl      | 6 - 4 | \-3.450 | \-5.484 | \-6.051  | \-3.893 |
|          |       | (2.463) | (1.539) | (1.712)  | (2.013) |
|          | 8 - 4 | \-5.820 | \-9.522 | \-10.055 | \-4.014 |
|          |       | (1.379) | (1.659) | (1.810)  | (2.707) |
| gear     | dY/dX |         |  0.361  |          |         |
|          |       |         | (1.094) |          |         |
|          | 4 - 3 |  3.041  |         |          |  1.187  |
|          |       | (1.687) |         |          | (2.414) |
|          | 5 - 3 |  0.768  |         |          | \-0.232 |
|          |       | (2.465) |         |          | (0.893) |
| wt       | dY/dX |         |         |          | \-3.721 |
|          |       |         |         |          | (1.220) |
| am       | 1 - 0 |         |         |          |  0.288  |
|          |       |         |         |          | (0.958) |
| Num.Obs. |       |   32    |   32    |    32    |   32    |
| R2       |       |  0.774  |  0.760  |  0.745   |  0.818  |
| R2 Adj.  |       |  0.696  |  0.725  |  0.718   |  0.765  |
| AIC      |       |  177.1  |  171.1  |  171.0   |  168.3  |
| BIC      |       |  191.8  |  179.9  |  178.3   |  181.5  |
| RMSE     |       |  2.82   |  2.90   |   2.99   |  2.53   |

**Closed** 2022-09-26 01:39 UTC

**Comment by grantmcdermott** [comment] 2022-09-26 01:45
Brilliant. We just about to jump on and test. Tagging @pbaylis who has also been looking for this functionality.
