### ISSUE TITLE
Marginal effects on fixest glm model is slow

### ISSUE THREAD

**Issue by maellecoursonnais** [vincentarelbundock/marginaleffects#485] opened 2022-09-12 16:16 UTC
Hi, 

First, thank you for all the efforts you put into this very important package. I am trying to compute marginal effects and predicted probabilities from a pretty large fixed-effect logistic regression. The command, however, is very slow and is thus not really usable. Do you see a reason for that?

Minimal example:

```r
library(fixest)
library(marginaleffects)
df <- data.frame(a = rnorm(1e6),
                 b = runif(1e6),
                 c = sample(290, 1e6, replace = T), 
                 d = sample(c(0, 1), 1e6, replace = T),
                 e = sample(1:5, 1e6, replace = T))

fe <- feglm(d ~ a + b  + i(e) + i(e, b) | c, data = df, family = "binomial")

predictions(fe, newdata = datagrid(model = fe, a = quantile(df$a), b = quantile(df$b)))
```
---
Edit: 
The function actually stopped and threw this error:

> Error: 
> Unable to compute adjusted predictions for model of class `fixest`. You can try to
> specify a different value for the `newdata` argument. If this does not work and
> you believe that this model class should be supported by `marginaleffects`,
> please file a feature request on the Github issue tracker:
> 
> https://github.com/vincentarelbundock/marginaleffects/issues
> In addition: Warning message:
> 
> Unable to extract predictions from a model of type `fixest`. Please
> report this problem, along with replicable code, on the `marginaleffects` issue tracker:
> https://github.com/vincentarelbundock/marginaleffects/issues
>

**Comment by vincentarelbundock** [comment] 2022-09-12 16:46
This minimal example runs in a fraction of a second on my computer.

Could you try updating the following package to the devel versions, restarting R, and trying again?

```r
library(remotes)
install_github("lrberge/fixest")
install_github("easystats/insight")
install_github("vincentarelbundock/marginaleffects")
```

**Comment by maellecoursonnais** [comment] 2022-09-12 17:29
You are right, it indeed was fast. I am trying to reproduce the problem. I added categorical variables in the original model.

**Comment by vincentarelbundock** [comment] 2022-09-12 18:06
I believe that this is a problem in the `is_fixest_call` and `is_calling_fun` functions from the `fixest` package. These functions take a *long* time to compute when `fixest` methods are called programmatically instead of directly. Here’s a benchmark showing that it takes much longer when using `do.call` rather than `predict()` directly:

``` r
library(fixest)
library(microbenchmark)

N <- 1e4
df <- data.frame(a = rnorm(N),
                 b = runif(N),
                 c = sample(290, N, replace = TRUE), 
                 d = sample(c(0, 1), N, replace = TRUE),
                 e = factor(sample(1:5, N, replace = TRUE)))
fe <- feglm(d ~ a + b  + i(e) | c, data = df, family = "binomial")

args <- list(object = fe, newdata = head(df), type = "response")

microbenchmark(
    predict(fe, newdata = head(df), type = "response"),
    do.call("predict", args),
    times = 3
)
#> Unit: milliseconds
#>                                                expr        min         lq
#>  predict(fe, newdata = head(df), type = "response")   4.280611   4.349286
#>                            do.call("predict", args) 441.219551 441.860392
#>        mean    median         uq        max neval cld
#>    4.435756   4.41796   4.513329   4.608698     3  a 
#>  444.097783 442.50123 445.536900 448.572566     3   b

**Comment by vincentarelbundock** [comment] 2022-09-12 18:13
It feels like this should be fixed upstream in `fixest`. We could potentially implement a workaround in `marginaleffects` by removing the 2 `do.call()` here: 

https://github.com/vincentarelbundock/marginaleffects/blob/main/R/methods_fixest.R#L47

And replacing them by a bunch of `if/else` structures to only include the relevant arguments in `predict()`. That seems inelegant, but it's probably not that much work. The issue is that I am swamped with the day job, so am unlikely to get to this in the near future. If you want to try to put together a PR, I'll gladly review it.

Thanks for the report!

**Comment by maellecoursonnais** [comment] 2022-09-13 10:27
I can try that. But honestly, I'm not sure how to start. Where can I find all the packages you are using in the function? e.g. for function `assert_dependency`, `sanitize_typ`... ?

So, just to be clear. The idea is to replace both `do.call` in lines 49 and 55 with direct `predict `calls, meaning that list of arguments would need to be detailed, since they cannot be put in a list for `predict`.

Why not use something like `predict(object = model, newdata = newdata, type = type, ...)`? Why are `if/else`s needed here?

**Comment by vincentarelbundock** [comment] 2022-09-13 12:14
Yeah, a couple simple `predict()` calls might work, depending on how `fixest` deals with unknown/unnecessary arguments.

The dev workflow would be to make changes to `methods_fixest.R`, load the changes, and run the test suite:

```r
library(pkgload)
library(tinytest)
setwd("path/to/the/git/repository")
load_all()
run_test_file("inst/tinytest/test-pkg-fixest.R")
```

**Closed** 2022-09-15 13:45 UTC
