### ISSUE TITLE
multiple imputation support for marginalmeans

### ISSUE THREAD

**Issue by nstjhp** [vincentarelbundock/marginaleffects#793] opened 2023-05-25 10:48 UTC
I hope this request makes sense. Following the article on Multiple Imputation and Missing Data I tried to use `marginalmeans()` with our multiply imputed data but this does not work. Error the same as below following the example. 

If it is not possible to update the function (is it enough to return the vcov object so we can then calculate `sqrt(diag(JVJ'))` ?), do you have any other advice on how we can get the marginal means following MI?

``` r
library(mice)
#> 
#> Attachement du package : 'mice'
#> L'objet suivant est masqué depuis 'package:stats':
#> 
#>     filter
#> Les objets suivants sont masqués depuis 'package:base':
#> 
#>     cbind, rbind
library(marginaleffects)
#> Warning: le package 'marginaleffects' a été compilé avec la version R 4.2.3
set.seed(1024)

dat <- iris
dat$Sepal.Length[sample(seq_len(nrow(iris)), 40)] <- NA
dat$Sepal.Width[sample(seq_len(nrow(iris)), 40)] <- NA
dat$Species[sample(seq_len(nrow(iris)), 40)] <- NA

dat_mice <- mice(dat, m = 20, printFlag = FALSE, .Random.seed = 1024)

mod_mice <- with(dat_mice, lm(Petal.Width ~ Sepal.Length * Sepal.Width + Species))

mfx_mice <- avg_slopes(mod_mice, by = "Species")
#> Warning in get.dfcom(object, dfcom): Infinite sample size assumed.
mfx_mice
#> 
#>          Term                        Contrast    Species Estimate Std. Error
#>  Sepal.Length mean(dY/dX)                     setosa       0.0684     0.0560
#>  Sepal.Length mean(dY/dX)                     versicolor   0.0540     0.0558
#>  Sepal.Length mean(dY/dX)                     virginica    0.0582     0.0512
#>  Sepal.Width  mean(dY/dX)                     setosa       0.1890     0.0836
#>  Sepal.Width  mean(dY/dX)                     versicolor   0.2092     0.0772
#>  Sepal.Width  mean(dY/dX)                     virginica    0.2242     0.1041
#>  Species      mean(versicolor) - mean(setosa) setosa       1.1399     0.0977
#>  Species      mean(versicolor) - mean(setosa) versicolor   1.1399     0.0977
#>  Species      mean(versicolor) - mean(setosa) virginica    1.1399     0.0977
#>  Species      mean(virginica) - mean(setosa)  setosa       1.7408     0.1108
#>  Species      mean(virginica) - mean(setosa)  versicolor   1.7408     0.1108
#>  Species      mean(virginica) - mean(setosa)  virginica    1.7408     0.1108
#>       t Pr(>|t|)   2.5 % 97.5 %
#>   1.222  0.22413 -0.0424  0.179
#>   0.968  0.33553 -0.0567  0.165
#>   1.137  0.25818 -0.0434  0.160
#>   2.260  0.02434  0.0246  0.353
#>   2.710  0.00807  0.0558  0.363
#>   2.155  0.03508  0.0162  0.432
#>  11.668  < 0.001  0.9464  1.333
#>  11.668  < 0.001  0.9464  1.333
#>  11.668  < 0.001  0.9464  1.333
#>  15.709  < 0.001  1.5214  1.960
#>  15.709  < 0.001  1.5214  1.960
#>  15.709  < 0.001  1.5214  1.960
#> 
#> Columns: term, contrast, Species, estimate, std.error, predicted, predicted_hi, predicted_lo, df, statistic, p.value, conf.low, conf.high

marg_means_mice = marginalmeans(mod_mice)
#> Error in as.data.frame.default(out): impossible de convertir automatiquement la classe '"mids"' en un tableau de données (data.frame)
```

<sup>Created on 2023-05-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment] 2023-05-25 11:37
thanks a lot for the report. Should be fixed in version 0.12.0.9003 available on Github.

**Closed by vincentarelbundock** 2023-05-25 11:37 UTC

**Comment by nstjhp** [comment] 2023-05-25 16:03
Thanks @vincentarelbundock for your swift response. This works well for linear models.
Is it possible to get it working for glms too?

For example, continuing from above, if I do 

```r
# Fake a binomial response
mod_mice <- with(dat_mice, glm(rbinom(n = length(Petal.Width), 1, 0.5) ~ Sepal.Length * Sepal.Width + Species, family = "binomial"))
marg_means_mice = marginal_means(mod_mice)
#>  Error in `[.data.frame`(x, , c("estimate", "std.error")) : 
#>   colonnes non définies sélectionnées
```

**Comment by vincentarelbundock** [comment] 2023-05-25 21:30
Thanks @nstjhp . This is kind of tricky. The problem is that for `glm()` models we report back-transformed confidence intervals by default and no standard errors. This prevents `mice` from combining estimates of uncertainty.

You can override this default behavior by specifying the scale explicitly with `type="response"`.

Version 0.12.0.9005 on Github will now return an informative error messages in that case.

**Comment by nstjhp** [comment] 2023-05-26 08:52
As my email response seems to be lost I will copy it here for the record:

> Yes that was what I understood was happening. Thanks for confirming.
> Are the SEs themselves sufficient for mice in this case? I had thought I needed the full vcov matrix?

If it's theoretically correct, then using `type = "response"` is now working well for me.
Thanks very much for your development and fast updating!
