### ISSUE TITLE
`plot_cap()` returns unexpected results when the predictor is a function

### ISSUE THREAD

**Issue by tomicapretto** [vincentarelbundock/marginaleffects#550] opened 2022-11-25 15:23 UTC
I'm trying to create a visualization with `plot_cap()` using a model that has transformations as predictors. Ultimately, I would like to be able to plot the results back in the original scale. But in the middle I faced another issue, which is the unexpected results when using `plot_cap()` with a model that contains a predictor that is a function transformation. See the examples below

Data preparation
```R
library(marginaleffects)

x = abs(rnorm(100, sd=5)) + 5
y = exp(2 + 0.3 * x + rnorm(100, sd=0.4))

data = data.frame(x=x, y=y)
data["log_x"] = log(x)
data["log_y"] = log(y)

plot(x=data$x, y=data$y)
```
![image](https://user-images.githubusercontent.com/25507629/204014982-9b0d7045-cd06-4f07-a941-62501ef4f0c3.png)

The following works well

```R
model <- lm(log_y ~ 1 + log_x, data=data)
plot_cap(model, condition="log_x")
```

![image](https://user-images.githubusercontent.com/25507629/204015058-d9648a76-deec-4694-947a-8a4ced5a4608.png)

But the following shows an unexpected result and produces warnings

```R
model <- lm(log(y) ~ 1 + log(x), data=data)
plot_cap(model, condition="x")
```
```
Warning message:
Removed 12 row(s) containing missing values (geom_path). 
```

![image](https://user-images.githubusercontent.com/25507629/204015131-56156eb7-5759-4557-beae-ea69d70b1ec8.png)

**Concretely**

* Is this a known issue?
* Is it possible to overcome this limitation?

Thanks a lot! 

By the way, I came across this because I'm implementing transformations for the `plot_cap()` version we have in Bambi and I'm not sure how to handle this exact case.

**Comment by vincentarelbundock** [comment] 2022-11-25 18:07
Thanks for the report; I was not aware of this problem.

I traced it back to an issue upstream in the `insight` package, and I opened an issue there: https://github.com/easystats/insight/issues/689

**Comment by tzoltak** [comment] 2022-12-05 18:24
The problem is probably in how `plot_cap()` (or something below it uses for this purpose) picks values of the (first) variable specified by the `condition` argument, at which it computes predictions.
The solution at hand is to use a custom defined grid in a workflow like this:
```r
dataToPredict <- datagrid(model = model,
                          x = seq(min(data$x), max(data$x),
                                      length.out = 20))
dataToPlot <- predictions(model, dataToPredict)
ggplot(dataToPlot,
       aes(x = x, y = predicted,
           ymin = conf.low, ymax = conf.high)) +
    geom_ribbon(alpha = 0.5) +
    geom_line(size = 1.2)
```

**Comment by vincentarelbundock** [comment] 2022-12-05 18:26
Yes, this workaround should work, but the `plot_cap` function will soon be fixed. There is work ongoing at the `insight` package to repair this, but it has proved to be more complicated than expected.

Shouldn't be too long before `plot_cap()` works as expected out of the box.

**Comment by tzoltak** [comment] 2022-12-05 19:00
I suspect this complication has something in common with the need to find the _original data_ passed to the model estimating function.

**Comment by vincentarelbundock** [comment] 2022-12-05 19:27
Yes, we know exactly what the complication is.

**Comment by vincentarelbundock** [comment] 2022-12-28 19:06
This problem is now fixed, but you must install the development versions of both `marginaleffects` and `insight`:

``` r
library(remotes)
install_github("easystats/insight")
install_github("vincentarelbundock/marginaleffects")
```

Thanks a lot for the report @tomicapretto and the suggestions @tzoltak. And sorry for the delay, but the problem was upstream and “infrastructure”-related.

``` r
library(marginaleffects)

x <- abs(rnorm(100, sd = 5)) + 5
y <- exp(2 + 0.3 * x + rnorm(100, sd = 0.4))
dat <- data.frame(x = x, y = y)
dat[["log_x"]] <- log(x)
dat[["log_y"]] <- log(y)

model <- lm(log(y) ~ 1 + log(x), data = dat)

plot_cap(model, condition = "x")
```

![](https://i.imgur.com/6yM6cJ4.png)

**Closed by vincentarelbundock** 2022-12-28 19:06 UTC
