### ISSUE TITLE
plotting predictions?

### ISSUE THREAD

**Issue by strengejacke** [vincentarelbundock/marginaleffects#664] opened 2023-02-10 09:27 UTC
Not exactly sure how to plot predictions - what do you think about adding a `plot()` method?

``` r
library(marginaleffects)

set.seed(123)
n <- 200
d <- data.frame(
  y = rnorm(n),
  cond = as.factor(sample(0:1, n, TRUE)),
  episode = as.factor(sample(0:4, n, TRUE)),
  sex = as.factor(sample(0:1, n, TRUE, prob = c(.4, .6)))
)
model1 <- lm(y ~ cond * episode, data = d)

plot(predictions(model1, newdata = datagrid(cond = 0:1, episode = 1:3)))
```

![](https://i.imgur.com/MJSWxNH.png)

``` r
plot_predictions(model1, newdata = datagrid(cond = 0:1, episode = 1:3))
#> Error: Assertion failed. One of the following must apply:
#>  * checkmate::check_character(condition): Must be of type 'character',
#>  * not 'NULL'
#>  * checkmate::check_list(condition): Must be of type 'list', not 'NULL'
```

<sup>Created on 2023-02-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment] 2023-02-10 11:55
What plot would you expect to get with this call?

**Comment by strengejacke** [comment] 2023-02-10 14:05
> And why not use the plot_predictions() function?

In the second example (with the error) I used `plot_predictions()`, but it failed.

> What plot would you expect to get with this call?

The one you generated in your example, but please, please, please, not again other arguments when I want to compute predicted values ;-)

I'd expect `plot()` to generate a plot with sensible defaults, and if any further customization is required, these can be additional arguments to `plot()` - but I don't want that `plot()` (or `plot_predictions()`) calculates predictions _and_ plots them. These are two steps and belong to two functions. Else, I would have to think how to produce predicted values in `plot_predictions()`, and the API / syntax is obviously different here (else, I wouldn't get the error I got, as seen in my initial post).

**Comment by vincentarelbundock** [comment] 2023-02-10 14:12
I agree that it would be nice for `plot()` to work on `predictions()` objects.

I agree that it would be nice for the arguments to be more consistent between `predictions()` and `plot_predictions()`.

I disagree that there should be two calls. There are *a ton* of packages in R which accept a fitted model and return plotted predictions. There's clear demand for this functionality. Ex: `jtools` and your own `ggpredict`

**Comment by vincentarelbundock** [comment] 2023-02-10 14:24
Marking this as duplicate of https://github.com/vincentarelbundock/marginaleffects/issues/647

**Closed by vincentarelbundock** 2023-02-10 14:24 UTC

**Comment by strengejacke** [comment] 2023-02-10 15:24
_ggeffects_ has a `plot()` method. 🙂

**Comment by strengejacke** [comment] 2023-02-10 16:12
Test, test, am I already blocked? 😬
<sup>(I'll try reading the vignettes more intensive before I continue complaining)</sup>
