### ISSUE TITLE
Consider adding ci_adjust, as per p_adjust, for predictions()

### ISSUE THREAD

**Issue by Chris-Larkin** [vincentarelbundock/marginaleffects#1181] opened 2024-07-25 11:13 UTC
As suggested in title. I am currently using something like:

`predictions(mod, newdata = datagrid(treatment_var = unique)` 

on a series of linear models to assess balance by covariates on treatment assignment. I have quite a few treatment conditions and so want to use `p_adjust` within `predictions`. In practice, i don't report out specific p-values, but I plot the means of my estimates with confidence intervals (as per the graph below). But when I specify `p_adjust = "bonferonni"` it drops the CIs instead of adjusting them. In my case, it would make more sense to me to use the adjusted p-value to adjust the CIs.

[balance_plot.pdf](https://github.com/user-attachments/files/16376673/balance_plot.pdf)

**Comment by vincentarelbundock** [comment] 2024-07-25 11:19
Closing as duplicate of https://github.com/vincentarelbundock/marginaleffects/issues/1169

**Closed** 2024-07-25 11:19 UTC

**Comment by Chris-Larkin** [comment] 2024-07-25 11:39
If anyone stumbles on this, I was basically able to get what I want by manually constructing the adjusted p-value and feeding 1-adjusted_p_value into the conf_level option. For example,

`predictions(mod, newdata = datagrid(treatment_var = unique), conf_level = 0.992)` 

I guess you could do something more like `1-(0.05/length(treatment_var))` to make it more flexible
