### ISSUE TITLE
Extracting coef for random effect levels

### ISSUE THREAD

**Issue by Marzie-Ynd** [vincentarelbundock/marginaleffects#1219] opened 2024-09-23 01:32 UTC
Hi @vincentarelbundock,

I am new to marginaleffects and I love it a lot. I faced an issue and I would appreciate your help. I need to extract the coef for the interaction term for each levels of a random intercept (in this example, islands):

```r
library(lme4)
library(tidyverse)
library(marginaleffects)

data <- read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/palmerpenguins/penguins.csv") %>%
  drop_na()

# model
model <- lmer(flipper_length_mm ~ bill_depth_mm*sex + (bill_depth_mm*sex | island),
              data = data)

summary(model)

# Overall interaction works nicely
plot_predictions(model, condition = c("bill_depth_mm", "sex"), re.form= NA)

slopes(model,
       variables = "bill_depth_mm",
       by="sex", 
       re.form = NA,
       hypothesis = "b2 = b1"
)

# Now, I need to extract the interaction coef for each island similar to what we get with ceof():
coef(model)
# (Intercept)    sexmale bill_depth_mm:sexmale
# Biscoe                -0.5713302
# Dream                  0.8860686
# Torgersen             -0.2444312

```
I used the following method which is not ideal. The `sequential` argument gives me unnecessary rows that i do not need so I had to remove them manually. Is it a better way to do so? 

```r
avg_slopes(model,
       variables = "bill_depth_mm",
       by= c("island","sex"), 
       re.form = NULL,
       hypothesis = "sequential") %>%
  tibble()%>%
  filter(str_detect(term, "female$")) %>%
  mutate(term = str_remove(term, ",.*"))
#term      estimate std.error statistic p.value s.value conf.low conf.high
#  <chr>        <dbl>     <dbl>     <dbl>   <dbl>   <dbl>    <dbl>     <dbl>
#1 Biscoe      -0.571     0.806    -0.709   0.478   1.06    -2.15       1.01
#2 Dream        0.886     0.796     1.11    0.266   1.91    -0.675      2.45
#3 Torgersen   -0.244     0.799    -0.306   0.760   0.397   -1.81       1.32
```

Moreover, my dataset has country with more than 70 countries and marginaleffects complains the number of rows that are above 25. Is it possible to get interaction coef for all countries in a single function or do I need separate dunctions?

And finally for my actual data, the SE is acting weird and is similar for all countries. Reading other posts, I realized that there is not a great way to extract coefs and SE and CI for random effect variables. Is it the reason?

Thank you so much in advance for your help.

**Comment by vincentarelbundock** [comment] 2024-09-23 01:44
Glad you like the package.

You can disable some safety checks with: `options(marginaleffects_safe = FALSE)`

`slopes()` does not estimate "interaction coefficients", so there is no such coefficient to extract. `slopes()` computes the partial derivative at a particular point in the predictor space. This is what the function returns.

If you want to compare slopes to one another, the `hypothesis` argument is the right place to look at.

`"sequential"` + post-computation filtering is probably the easiest approach. But you could look into defining your own custom function for `hypothesis`. This is well documented on the website.

Not sure what you mean about standard errors, but I imagine it could have something to do with `re.form=NA`.

closing this issue because it is not a bug report or a feature request.

**Closed by vincentarelbundock** 2024-09-23 01:44 UTC
