### ISSUE TITLE
plot_cme returns Error in if (num > 1e+09) { : argument is of length zero 

### ISSUE THREAD

**Issue by mattwilliamson13** [vincentarelbundock/marginaleffects#489] opened 2022-09-20 14:44 UTC
Hello,
I'm trying to plot the marginal effects of a varying intercept/varying slope model fit using the `nl=TRUE` option for `brms`. The model looks like:
```
brm(data=df.long, 
            family = cumulative(probit),
            formula = bf(adjrating ~  1 + ideology + issue + gender + education + age,
                         ideology ~ ideology + (ideology|issue),
                         issue ~ 0 + (1|issue),
                         gender ~ 0 + (1|gender),
                         education ~ 0 + mo(education),
                         age ~ 0 + age_scl,
                         nl = TRUE),
            prior = c(prior(student_t(3,0,1.5), class = b, nlpar="ideology"),
                      prior(student_t(3,0,1.5), class = sd, nlpar="ideology"),
                      prior(student_t(3,0,1.5), class = sd, nlpar="issue"),
                      prior(student_t(3,0,1.5), class = sd, nlpar="gender"),
                      prior(student_t(3,0,1.5), class= b,  nlpar = "age"),
                      prior(student_t(3,0,1.5), class= b, nlpar="education"),
                      prior(dirichlet(c(1,1, 1,1, 2, 2)), class = "simo", coef = "moeducation1", nlpar="education")),
            chains = 5,
            cores = 5,
            iter=2000,
            init = 0.2,
            seed = 1,
            backend = "cmdstanr", 
            threads = threading(5),
            control=list(max_treedepth = 18, adapt_delta=0.9)
)
```

There are a couple of tricky bits happening here. First, I'm using the index notation (rather than treating the categorical variables of issue, gender, and education as factors). Second, because I'm using the `nl` notation terms in the model do not correspond 1:1 with terms in the data (like `age ~ 0 + age_scl`).

I've checked the underlying function call and can't find where the `if` statement referenced in the error is actually being triggered, but I'm wondering if it has something to do with the fact that plot_cme is trying to treat each index variable as numeric rather than categorical? Or if it's because the `nl` syntax isn't currently supported. Any advice you have would be great. FWIW - I'm trying to plot the marginal effects of ideology for each level of issue. 
Thanks in advance!

**Comment by vincentarelbundock** [comment] 2022-09-20 15:19
Thanks for the report, but I can't really diagnose without a minimal working example using public data. See here for tips on how to compose a MWE: https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html

Do the `predictions()` and `marginaleffects()` functions work?

**Comment by mattwilliamson13** [comment] 2022-09-20 20:06
Thanks @vincentarelbundock. I'm working on a reprex now. A few updates:
1) changing to using the factor notation (instead of integer indices) doesn't fix this
2) `predictions()` and `marginaleffects()` both fail with the same error message:
```
nable to compute adjusted predictions for this model. Either the
`newdata` does not meet the requirements of the model's `predict()`
method, or this model is not supported. If you believe this model
should be supported, you can file a report on the Github Issue Tracker:
https://github.com/vincentarelbundock/marginaleffects/issues
 

In addition: Error in get(v, newdata): object 'education' not found
```
This last piece suggests to me that it might not actually be the varying effects part of the model, but rather, the monotonic specification (`mo(education)`). As you can see from the `prior` call, the `mo` call changes the names of the variables a bit.

**Comment by mattwilliamson13** [comment] 2022-09-20 21:20
Ok, here's a reprex that relies on simulated data
```
library(tidyverse) #for data manipulation
library(brms) #for analysis and Dirichlet distr
library(tidybayes)
library(marginaleffects)

set.seed(5)  # used to replicate example
n_category_age <-  5
n_category_sex <- 3
a_sex <- rnorm(n_category_sex, 0, 1)
a_age <- rnorm(n_category_age, 0, 1)
n_obs <- 2000
obs_age <- sample(1:n_category_age, n_obs, replace=TRUE)
obs_sex <- sample(1:n_category_sex, n_obs, replace=TRUE)
b_ed <- rnorm(1,0,0.5) #overall size of education effect
n_category_ed <- 5
D <-  n_category_ed - 1
zeta <- c(0,brms::rdirichlet(n=1, alpha = c(1,1,2,1))) #we add a 0 to this vector so that when x=1 (the lowest category), no distance is used
sum(zeta)
ed_options <- c("dnf_high_school","high_school", "some_college", "bachelors", "graduate")
obs_ed <-factor(sample(ed_options, n_obs, TRUE, prob=c(0.2,0.2,0.3,0.2,0.1)),
                     levels = ed_options, ordered = TRUE)

eta <- unlist(lapply(1:n_obs, function(x) b_ed * D * sum(zeta[1:obs_ed[x]])))
a       <-  -0.2
b       <- 0.5    # average difference in appropriateness due to country
sigma_a <-  1    # std dev in intercepts
sigma_b <-  1  # std dev in slopes
rho     <- -.6   # correlation between intercepts and slopes

# the next three lines of code simply combine the terms, above
mu     <- c(a, b)

cov_ab <- sigma_a * sigma_b * rho
sigma  <- matrix(c(sigma_a^2, cov_ab, 
                   cov_ab, sigma_b^2), ncol = 2)
sigmas <- c(sigma_a, sigma_b)          # standard deviations
rho    <- matrix(c(1, rho,             # correlation matrix
                   rho, 1), nrow = 2)

# now matrix multiply to get covariance matrix
sigma <- diag(sigmas) %*% rho %*% diag(sigmas)

# how many countries would you like?
n_country <- 10



vary_effects <- 
  MASS::mvrnorm(n_country, mu, sigma) %>% 
  data.frame() %>% 
  set_names("a_country", "b_country")
obs_cty <- sample(1:n_country, n_obs, replace=TRUE)


obs_ideology <- sample.int(7, n_obs, replace = TRUE, prob = c(0.05, 0.1, 0.2, 0.3, 0.2, 0.1, 0.05)) #we have 7 levels of ideology from left to right, could include prob statement to get more uneven sampling

rating_linpred <- vary_effects[obs_cty,1] + a_sex[obs_sex] + a_age[obs_age] + vary_effects[obs_cty,2]*obs_ideology 
uneven_thresholds <- tibble(rating = 1:5) %>% 
  mutate(proportion = c(1/10, 1/5,2/5,1/5,1/10)) %>% 
  mutate(cumulative_proportion = cumsum(proportion)) %>% 
  mutate(right_hand_threshold = qnorm(cumulative_proportion))



uneven_tau <- uneven_thresholds$right_hand_threshold[1:n_tau]
probs <- matrix(nrow=n_obs, ncol=(n_tau + 1)) #need probability of landing in last group

probs[,1] <- pnorm(uneven_tau[1], mean=0 + rating_linpred)
probs[,2] <- pnorm(uneven_tau[2],  mean=0 + rating_linpred) - pnorm(uneven_tau[1], mean=0 + rating_linpred)
probs[,3] <- pnorm(uneven_tau[3],  mean=0 + rating_linpred) - pnorm(uneven_tau[2], mean=0 + rating_linpred)
probs[,4] <- pnorm(uneven_tau[4],  mean=0 + rating_linpred) - pnorm(uneven_tau[3], mean=0 + rating_linpred)
probs[,5] <- 1 - pnorm(uneven_tau[4], mean=0 + rating_linpred)

uneven_rating <- vector(mode="integer", length = n_obs)

for(i in 1:nrow(probs)){
  uneven_rating[i] <- sample(x=1:5, size=1, prob=c(probs[i,]))
}
df <- data.frame(cbind(obs_cty, obs_age, obs_sex, obs_ed, obs_ideology, uneven_rating))

fit3a <- brm(
  data = df,
  family = cumulative(probit),
  formula = bf(uneven_rating ~  1 + age + sex + ed + ideology,
               age ~ 0 + (1|obs_age),
               sex ~ 0 + (1|obs_sex),
               ideology ~ obs_ideology + (obs_ideology|obs_cty),
               ed ~ 0 + mo(obs_ed),
               nl=TRUE),
  prior = c(prior(normal(-0.84, 2), class = Intercept, coef = 1),
            prior(normal(-0.25, 2), class = Intercept, coef = 2),
            prior(normal(0.25, 2), class = Intercept, coef = 3),
            prior(normal(0.84, 2), class = Intercept, coef = 4),
            prior(normal(0,1), class= sd,  nlpar = "age"),
            prior(normal(0,1), class= sd, nlpar="sex"),
            prior(normal(0, 1), class= b, nlpar="ed"),
            prior(dirichlet(c(1,1, 2, 1)), class = "simo", coef = "moobs_ed1", nlpar="ed"),
            prior(normal(0, 1), class = b, nlpar="ideology"),
            prior(normal(0,1), class = sd, nlpar="ideology"),
            prior(lkj(2), class = cor)),
  cores = 4,
  seed = 1,
  init_r = 0.2,
  control=list(max_treedepth = 15, adapt_delta=0.9)
)
predictions(fit3a)
```

If it's helpful, I can point you to a quaro doc that has more explanation of the case...

**Comment by vincentarelbundock** [comment] 2022-09-21 23:04
Code does not run. `n_tau` undefined.

**Comment by mattwilliamson13** [comment] 2022-09-21 23:12
Edited. Sorry I missed that.

**Comment by vincentarelbundock** [comment] 2022-09-21 23:40
Thanks. I believe that this is an upstream problem in the `insight` package. I opened an issue with some hints for diagnosis, but I'm not exactly sure what the problem is or how to fix it. See here for the details I could find:

https://github.com/easystats/insight/issues/645

**Comment by vincentarelbundock** [comment] 2022-09-24 13:18
When this is fixed upstream, I expect `marginaleffects` to start working automatically. In the meantime, you can make the functions work by supplying the data frame explicitly to the `newdata` argument as follows:

```r
library(brms)
library(marginaleffects)

mod <- brm(
    data = mtcars,
    backend = "cmdstanr",
    family = cumulative(probit),
    formula = bf(
        cyl ~ 1 + mpg + drat + gearnl,
        gearnl ~ 0 + (1 | gear),
        nl = TRUE))

marginaleffects(mod, newdata = mtcars)
```

I also improved the error message to give a hint to use the `newdata` argument.

I will close this now as there is no more action to be taken in this repository. I'll try to look at the upstream issue eventually, but I'm not sure exactly how to fix this.

**Comment by vincentarelbundock** [comment] 2022-09-27 21:51
@mattwilliamson13 what version of the package are you using? Could you try installing from Github

**Comment by vincentarelbundock** [comment] 2022-10-05 13:53
I don't understand what you mean. When I run the long reprex that you wrote in the 3rd post, I call `predictions(fit3a, newdata=df)` and I get 5 response levels, which seems consistent with the data generating process.

And please note that the upstream problem I linked to in the `insight` repository is not fixed yet.

**Comment by vincentarelbundock** [comment] 2022-10-12 12:25
https://github.com/easystats/insight/issues/645

With the change in the `insight` package above and the latest dev version of `marginaleffects`, I believe this is now fixed. You can try the new versions with:

```r
remotes::install_github("easystats/insight")
remotes::install_github("vincentarelbundock/marginaleffects")
```

Restart R and try again.

Note that the `plot_cap()` and `plot_cme()` functions will not work out of the box in your long example. This is because the `predict()` method in `brms` apparently expects integer predictors for this specific model, but the `plot_*()` assume that the x-axis variable is either a continuous numeric or a factor. This feels like a quirk of the model rather than a problem in `marginaleffects`. You may want to convert the variables to factor before fitting the model. Alternatively, it is trivial to build a data frame with `predictions()` and feed that in `ggplot2`, so it's probably not a big problem.

Feel free to open a new issue with a minimal reproducible example if it doesn't work for you.

Thanks again for the report!

**Closed by vincentarelbundock** 2022-10-12 12:25 UTC
