### ISSUE TITLE
Default value of the `dpar` argument in `brms` models

### ISSUE THREAD

**Issue by piotrkoc** [vincentarelbundock/marginaleffects#405] opened 2022-07-17 18:00 UTC
Hi,

I estimated a zero-inflated beta-binomial model with random intercepts in brms with the same predictors for mu and zi. I wanted to compute marginal effects for one of the predictors using the followig syntax:

```
mfx <- marginaleffects(brms_fit,
                       type = "link",
                       dpar = "mu",
                       re_formula = NA,
                       variables = "gndr") |>
  posteriordraws()
```
But then I saw that without specifying the dpar argument, i.e. 

```
mfx <- marginaleffects(all,
                       type = "link",
                       re_formula = NA,
                       variables = "gndr") |>
  posteriordraws()
```
I get exactly the same results. When I specify dpar = "zi", everything seems to be fine.

Is there a way to get marginal effects for the non-zero, mu, part only?

**Comment by vincentarelbundock** [comment] 2022-07-17 18:23
What arguments would you use in the standard `brms::posterior_epred` function?

**Comment by piotrkoc** [comment] 2022-07-17 18:58
I guess I'd write something like: 
`posterior_epred(brms_fit, newdata, dpar = "mu", re_formula = NULL)`

**Comment by vincentarelbundock** [comment] 2022-07-17 18:59
And does this produce different results when you change the `dpar` argument? I'd just like to be sure that this is not an upstream issue. The `dpar` parameter is just pushed through the `...` to `brms::posterior_epred`, so my hunch is that you probably have the same problem if you just use that...

**Comment by piotrkoc** [comment] 2022-07-17 19:26
I checked it quickly by running:
```
test <- posterior_epred(all, newdata, dpar = "mu", re_formula = NA)
test1 <- posterior_epred(all, newdata, re_formula = NA)
```
and the distributions seem to be be different: 
![dpar](https://user-images.githubusercontent.com/90638828/179421652-d56e52dc-c1cc-422a-85b2-52b00204d424.png)

**Comment by vincentarelbundock** [comment] 2022-07-17 19:31
thanks.

Is this a model in one of the vignettes? If not, could you give me a minimal reproducible example with publicly available data?

**Comment by piotrkoc** [comment] 2022-07-17 19:39
I will try to cook up an example.

**Comment by piotrkoc** [comment] 2022-07-18 10:36
So I found a dataset (it took me a while...) - https://www.jstatsoft.org/article/view/v016i09 
I used the following variables:  
**ofp** - number of physician office visits as the dependent variable;  and as regressors: 
**hosp** - number of hospital stays; **health** - self-perceived health status; **numchron** - number of chronic conditions; **gender**, **school** - number of years of education; and **privins** - private insurance indicator.
I added a variable denoting the number of trials, trls = max (ofp) , just to be able to fit a zero-inflated beta-binomial. 

```
getwd()
load("DebTrivedi.rda")
df <- DebTrivedi[,c("ofp", "hosp", "health", "numchron", "gender", "school", "privins")]

df <- subset(df, ofp < 40)
df$trls <- max(df$ofp)

f_zibb <- bf(ofp| trials(trls) ~ 1 + hosp + health + numchron + gender + school + privins,
           zi ~ 1 + hosp + health + numchron + gender + school + privins)

zibb <- 
  brm(data = df, 
      family = zero_inflated_beta_binomial(),
      formula = f_zibb,
      prior = c(prior(normal(0, 1.5), class = Intercept),
                prior(normal(0, 1), class = b),
                prior(exponential(.1), class = phi),
                prior(normal(0, 1), class = b, dpar = zi),
                prior(logistic(0, 1), class = Intercept, dpar = zi)),
      chains = 4,
      cores = 4,
      init = 0,
      iter = 2000,
      seed = 2376,
      backend = "cmdstanr")
```
Now, the marginaleffects() would produce different outputs for dpar = "mu" and dpar = NULL, if the type is set to "response". 

```
> marginaleffects(zibb, variables = "hosp") |> summary()
Average marginal effects 
  Term Effect  2.5 % 97.5 %
1 hosp  1.034 0.8558  1.209

Model type:  brmsfit 
Prediction type:  response 
```
```
> marginaleffects(zibb, dpar = "mu", variables = "hosp") |> summary()
Average marginal effects 
  Term  Effect   2.5 % 97.5 %
1 hosp 0.02722 0.02263 0.0317

Model type:  brmsfit 
Prediction type:  response 
```

When we set the type = "link", then the function seems to ignore the dpar argument. 

```
> marginaleffects(zibb, variables = "hosp", type = "link") |> summary()
Average marginal effects 
  Term Effect  2.5 % 97.5 %
1 hosp 0.2265 0.1885 0.2633

Model type:  brmsfit 
Prediction type:  link 
```
```
> marginaleffects(zibb, dpar = "mu", variables = "hosp", type = "link") |> summary()
Average marginal effects 
  Term Effect  2.5 % 97.5 %
1 hosp 0.2265 0.1885 0.2633

Model type:  brmsfit 
Prediction type:  link 
```

**Comment by vincentarelbundock** [comment] 2022-07-23 16:48
Thanks a lot for this example, it was very useful. It looks like this is an upstream problem: `brms` prediction functions use different `dpar` values as defaults. I recommend that you always specify `dpar` explicitly instead of relying on an unspecified default value.

Example:

``` r
# linkpred (type = "link") uses "mu" as default
brms::posterior_linpred(zibb)[1:2, 1:2]
#>           [,1]      [,2]
#> [1,] -1.737827 -1.708591
#> [2,] -1.767806 -1.674070
brms::posterior_linpred(zibb, dpar = "mu")[1:2, 1:2]
#>           [,1]      [,2]
#> [1,] -1.737827 -1.708591
#> [2,] -1.767806 -1.674070
brms::posterior_linpred(zibb, dpar = "zi")[1:2, 1:2]
#>           [,1]      [,2]
#> [1,] -6.897247 -6.936487
#> [2,] -5.484106 -6.876942

# epred (type="response") uses neither "mu" nor "zi"
brms::posterior_epred(zibb)[1:2, 1:2]
#>          [,1]     [,2]
#> [1,] 5.828087 5.974710
#> [2,] 5.663283 6.151066
brms::posterior_epred(zibb, dpar = "mu")[1:2, 1:2]
#>           [,1]      [,2]
#> [1,] 0.1495892 0.1533466
#> [2,] 0.1458153 0.1578823
brms::posterior_epred(zibb, dpar = "zi")[1:2, 1:2]
#>             [,1]         [,2]
#> [1,] 0.001009543 0.0009707339
#> [2,] 0.004135076 0.0010302305
```

**Comment by vincentarelbundock** [comment] 2022-07-26 11:32
Since this appears to be an upstream issue in `brms`, and since there seems to be an easy solution, I will close this issue. Please feel free to keep the discussion going if you think something specific should be changed in `marginaleffects`.

**Closed by vincentarelbundock** 2022-07-26 11:32 UTC
