### ISSUE TITLE
`glmmTMB` models with `REML = TRUE`

### ISSUE THREAD

**Issue by SchmidtPaul** [vincentarelbundock/marginaleffects#466] opened 2022-08-22 12:36 UTC
Edit: collapsed outdated initial comment.

<details>
<summary>Click to expand</summary>

Hi, I received the following error
```r
#> Error: Could not manipulate the coefficients of this `glmmTMB` model object. 
#> Please report this error on the `marginaleffects` Github issue tracker with the data 
#> and code necessary to replicate the problem: https://github.com/vincentarelbundock/marginaleffects/issues
```
so here I am. It seems to only happen with `REML = TRUE`:

``` r

library(glmmTMB)
library(marginaleffects)
library(tidyverse)
set.seed(42)

dat <- bind_rows(
  PlantGrowth %>% mutate(trial = "A"),
  PlantGrowth %>% mutate(trial = "B", weight = runif(30) * weight),
  PlantGrowth %>% mutate(trial = "C", weight = runif(30) * weight)
)

mod_ML <- glmmTMB(
  weight ~ group + trial + (1 | group:trial),
  REML = FALSE,
  data = dat
)

mod_REML <- glmmTMB(
  weight ~ group + trial + (1 | group:trial),
  REML = TRUE,
  data = dat
)

# predictions -------------------------------------------------------------
p_ML   <- predictions(mod_ML)
p_REML <- predictions(mod_REML)
#> Error: Could not manipulate the coefficients of this `glmmTMB` model object. Please report this error on the `marginaleffects` Github issue tracker with the data and code necessary to replicate the problem: https://github.com/vincentarelbundock/marginaleffects/issues
```

<sup>Created on 2022-08-22 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

</details>

**Comment by vincentarelbundock** [comment] 2022-08-22 16:53
Thanks a lot for the report.

The problem is that the generic strategy we use to compute standard errors (delta method) requires us to modify the parameters of the model before making predictions. AFAICT, these parameters are hosted in `model$fit$par`, but that object does not include all the parameters when `REML=TRUE`. So when we set `set_coef()`, we can't change the fixed effects, and the predictions are not altered. In turn, this produced 0 standard errors in `get_se_delta()`.

All this to say that I don't quite know how to support standard errors when `REML=TRUE`. Perhaps a `glmmTMB` expert will be able to find a solution, but for now I have pushed a commit with a more informative error message, tell using to either turn `REML=FALSE`, or `vcov=FALSE`.

**Comment by vincentarelbundock** [comment] 2022-08-22 18:27
For reference, this is the code we use to set the coefficients of a model: https://github.com/vincentarelbundock/marginaleffects/blob/main/R/methods_glmmTMB.R#L42

**Comment by SchmidtPaul** [comment] 2022-08-23 06:55
I think I have a follow-up question. I tried a quite ugly workaround by first fitting the model via REML and extracting the values for the estimated variance components. Then, I can fit a model with `REML=FALSE` but actually hold all mentioned values to the extracted values from the REML-model (see glmmTMB/glmmTMB#833 for details on how to do that). 

Yet, this approach also gives me the error message - even for this model with `REML=FALSE`:

``` r
library(emmeans)
library(glmmTMB)
library(marginaleffects)
library(tidyverse)
set.seed(42)

dat <- bind_rows(
  PlantGrowth %>% mutate(trial = "A"),
  PlantGrowth %>% mutate(trial = "B", weight = runif(30) * weight),
  PlantGrowth %>% mutate(trial = "C", weight = runif(30) * weight)
)


# Run REML model to extract variance components ---------------------------
mod_REML <- glmmTMB(
  weight ~ group + trial + (1 | group:trial),
  REML = TRUE,
  data = dat
)

broom.mixed::tidy(mod_REML) %>% 
  filter(effect == "ran_pars")
#> # A tibble: 2 × 8
#>   effect   component group       term            estim…¹ std.e…² stati…³ p.value
#>   <chr>    <chr>     <chr>       <chr>             <dbl>   <dbl>   <dbl>   <dbl>
#> 1 ran_pars cond      group:trial sd__(Intercept) 1.09e-4      NA      NA      NA
#> 2 ran_pars cond      Residual    sd__Observation 1.37e+0      NA      NA      NA
#> # … with abbreviated variable names ¹​estimate, ²​std.error, ³​statistic


# Run "ML" model but fix variance components to REML values ---------------
mod_pseudoREML <- glmmTMB(
  weight ~ group + trial + (1 | group:trial),
  REML = FALSE,
  start = list(theta = log(0.000109),  betad = log(1.37^2)), # for some reason theta is log(sd), while betad is log(var); see mentioned issue above
  map   = list(theta =    factor(NA),  betad = factor(NA)),
  data = dat
)

# predictions -------------------------------------------------------------
p_REML       <- predictions(mod_REML)
#> Error: Could not manipulate the coefficients of this `glmmTMB` model object. Please report this error on the `marginaleffects` Github issue tracker with the data and code necessary to replicate the problem: https://github.com/vincentarelbundock/marginaleffects/issues
p_pseudoREML <- predictions(mod_pseudoREML)
#> Error: Could not manipulate the coefficients of this `glmmTMB` model object. Please report this error on the `marginaleffects` Github issue tracker with the data and code necessary to replicate the problem: https://github.com/vincentarelbundock/marginaleffects/issues
```

<sup>Created on 2022-08-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment] 2022-08-23 09:38
Can you try with the latest version from GitHub, making sure to restart after install?

**Comment by SchmidtPaul** [comment] 2022-08-23 10:04
Yeah, sorry. Apparently the `REML=TRUE` is no longer a problem?!

``` r
library(emmeans)
library(glmmTMB)
library(marginaleffects)
library(dplyr)
set.seed(42)

dat <- bind_rows(
  PlantGrowth %>% mutate(trial = "A"),
  PlantGrowth %>% mutate(trial = "B", weight = runif(30) * weight),
  PlantGrowth %>% mutate(trial = "C", weight = runif(30) * weight)
)


# Run REML model to extract variance components ---------------------------
mod_REML <- glmmTMB(
  weight ~ group + trial + (1 | group:trial),
  REML = TRUE,
  data = dat
)

broom.mixed::tidy(mod_REML) %>% 
  filter(effect == "ran_pars")
#> # A tibble: 2 × 8
#>   effect   component group       term            estim…¹ std.e…² stati…³ p.value
#>   <chr>    <chr>     <chr>       <chr>             <dbl>   <dbl>   <dbl>   <dbl>
#> 1 ran_pars cond      group:trial sd__(Intercept) 1.09e-4      NA      NA      NA
#> 2 ran_pars cond      Residual    sd__Observation 1.37e+0      NA      NA      NA
#> # … with abbreviated variable names ¹​estimate, ²​std.error, ³​statistic


# Run "ML" model but fix variance components to REML values ---------------
mod_pseudoREML <- glmmTMB(
  weight ~ group + trial + (1 | group:trial),
  REML = FALSE,
  start = list(theta = log(0.000109),  betad = log(1.37^2)),
  map   = list(theta =    factor(NA),  betad = factor(NA)),
  data = dat
)

# predictions -------------------------------------------------------------
predictions(mod_REML) %>% head()
#>   rowid     type group predicted    std.error statistic p.value conf.low
#> 1     1 response  ctrl  5.096665 3.189829e-05  159778.6       0 5.096602
#> 2     2 response  ctrl  5.096665 3.189829e-05  159778.6       0 5.096602
#> 3     3 response  ctrl  5.096665 3.189829e-05  159778.6       0 5.096602
#> 4     4 response  ctrl  5.096665 3.189829e-05  159778.6       0 5.096602
#> 5     5 response  ctrl  5.096665 3.189829e-05  159778.6       0 5.096602
#> 6     6 response  ctrl  5.096665 3.189829e-05  159778.6       0 5.096602
#>   conf.high weight trial
#> 1  5.096727   4.17     A
#> 2  5.096727   5.58     A
#> 3  5.096727   5.18     A
#> 4  5.096727   6.11     A
#> 5  5.096727   4.50     A
#> 6  5.096727   4.61     A
predictions(mod_pseudoREML)
#> Error: The Jacobian does not match the variance-covariance matrix.
```

<sup>Created on 2022-08-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details>
  <summary>Session Info</summary>

``` r
sessionInfo()
#> R version 4.2.1 (2022-06-23 ucrt)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 19044)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=German_Germany.utf8  LC_CTYPE=German_Germany.utf8   
#> [3] LC_MONETARY=German_Germany.utf8 LC_NUMERIC=C                   
#> [5] LC_TIME=German_Germany.utf8    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] rstudioapi_0.14   knitr_1.39        magrittr_2.0.3    R.cache_0.16.0   
#>  [5] rlang_1.0.4       fastmap_1.1.0     fansi_1.0.3       stringr_1.4.1    
#>  [9] styler_1.7.0      highr_0.9         tools_4.2.1       xfun_0.32        
#> [13] R.oo_1.25.0       utf8_1.2.2        cli_3.3.0         withr_2.5.0      
#> [17] htmltools_0.5.3   yaml_2.3.5        digest_0.6.29     tibble_3.1.8     
#> [21] lifecycle_1.0.1   purrr_0.3.4       R.utils_2.12.0    vctrs_0.4.1      
#> [25] fs_1.5.2          glue_1.6.2        evaluate_0.16     rmarkdown_2.15   
#> [29] reprex_2.0.2      stringi_1.7.8     compiler_4.2.1    pillar_1.8.1     
#> [33] R.methodsS3_1.8.2 pkgconfig_2.0.3
```

<sup>Created on 2022-08-23 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

</details>

**Comment by vincentarelbundock** [comment] 2022-08-23 10:14
Right. So REML is allowed in `predictions()`, by delegating to the ˋinsight`, but it won't work with the other functions in the package (ex: `marginaleffects()`)

**Comment by vincentarelbundock** [comment] 2022-08-23 16:25
Since I don't plan to work on this in the near term, I will clean up the repo and close this issue now.

However, if you or another `glmmTMB` expert wants to work on this, please feel free to re-open this issue, keep commenting, or open a new Issue (or even better: a Pull Request).

**Closed** 2022-08-23 16:29 UTC
